/**
 * Physician FAQ — Personalized answers for patient advocacy
 *
 * Structure: PHYSICIAN_FAQ_DATA[cancerType][concernId] = { ... }
 *
 * Cancer type tiers:
 *   Tier 1 (full): colorectal, breast, lung
 *   Tier 2 (moderate): bladder, melanoma
 *   Tier 3 (generic): everything else uses '_default'
 *
 * Stage-specific notes are optional overlays on the base answer.
 *
 * Generated by: node evidence/scripts/render-faq.js
 * Last rendered: 2026-05-09
 */

export const CONCERNS = [
  { id: 'no-evidence', label: '"There\'s no evidence MRD results change outcomes."' },
  { id: 'not-in-guidelines', label: '"It\'s not in the guidelines yet."' },
  { id: 'what-to-do-positive', label: '"What would I even do with a positive result?"' },
  { id: 'insurance', label: '"Insurance won\'t cover it."', isWizardLink: true },
  { id: 'not-validated', label: '"The test isn\'t validated for your cancer type."' },
];

// Helper to get the best answer for a cancer type, falling back to _default
export function getAnswer(cancerType, concernId) {
  const typeData = PHYSICIAN_FAQ_DATA[cancerType] || PHYSICIAN_FAQ_DATA['_default'];
  return typeData[concernId] || PHYSICIAN_FAQ_DATA['_default'][concernId];
}

// Helper to get stage-specific note
export function getStageNote(cancerType, concernId, stage) {
  const answer = getAnswer(cancerType, concernId);
  if (!answer?.stageNotes || !stage) return null;
  return answer.stageNotes[stage] || null;
}

export const PHYSICIAN_FAQ_DATA = {

  /* ═══════════════════════════════════════════
   *  COLORECTAL — Tier 1 (strongest evidence)
   * ═══════════════════════════════════════════ */
  colorectal: {
    'no-evidence': {
      forPatient: 'While your doctor is right that we\'re still building evidence on whether MRD testing directly improves survival, recent studies like DYNAMIC show that ctDNA testing can safely guide treatment decisions - allowing many patients to avoid unnecessary chemotherapy while maintaining the same cancer-free survival rates. The GALAXY study also found that patients with positive ctDNA tests who received chemotherapy had much better outcomes than those who didn\'t, suggesting the test results can help identify who really needs treatment.',
      forDoctor: 'Recent RCT evidence demonstrates clinical utility of MRD testing in guiding treatment decisions. The DYNAMIC trial (N=455, PMID: 35657320) showed ctDNA-guided management reduced adjuvant chemotherapy use from 28% to 15% in stage II CRC while maintaining non-inferior 2-year RFS (93.5% vs 92.4%, HR 0.92) and equivalent 5-year outcomes (RFS 88% vs 87%, OS 93.8% vs 93.3%, HR 1.05, P=0.887). The GALAXY/VEGA study (N>2000, PMID: 36646802) demonstrated that ctDNA+ patients receiving adjuvant chemotherapy had significantly improved DFS vs observation (HR 0.39), with ctDNA+ patients showing markedly worse outcomes than ctDNA- patients (DFS HR 11.99, OS HR 9.68). The ALTAIR trial showed treatment benefit in ctDNA+ patients with FTD/TPI vs placebo (median DFS 9.23 vs 5.55 months, HR 0.75, P=0.0406). While escalation strategies haven\'t shown definitive DFS gains, de-escalation approaches have proven safe and reduce toxicity without compromising outcomes.',
      stageNotes: {
        'stage-1': 'ALTAIR trial included stage I patients showing treatment benefit with FTD/TPI in ctDNA-positive cases.',
        'stage-2': 'DYNAMIC trial specifically demonstrated safe ctDNA-guided chemotherapy de-escalation in stage II CRC with equivalent long-term outcomes.',
        'stage-3': 'Multiple studies including GALAXY/VEGA and Guardant Reveal show strong prognostic value in stage III disease, with ATOMIC supporting atezolizumab plus chemotherapy for dMMR tumors.',
        'stage-4': 'ALTAIR trial demonstrated treatment benefit with FTD/TPI in ctDNA-positive metastatic patients.',
      },
      sources: [
        { label: 'Tie et al., New England Journal of Medicine, 2022, - Circulating tumor DNA analysis guiding adjuvant therapy in stage II colon cancer', pmid: '35657320' },
        { label: 'Tie et al., Nature Medicine, 2025, - DYNAMIC 5-year follow-up', pmid: '40055522' },
        { label: 'Kotani et al., Nature Medicine, 2023, - GALAXY/VEGA study', pmid: '36646802' },
        { label: 'ALTAIR investigators, 2026, - ALTAIR trial' },
        { label: 'CITCCA investigators, 2026, - CITCCA study' },
        { label: 'Guardant investigators, Journal of Clinical Oncology, 2026, - Guardant Reveal stage III CRC study' },
        { label: 'Reinert et al., JAMA Oncology, 2019, - Analysis of ctDNA to Predict Outcome after Surgery and Adjuvant Treatment in Colorectal Cancer', pmid: '31070691' },
        { label: 'Jiang et al., J Gastrointest Surg, 2026, - The role of ctDNA in precision adjuvant therapy for colorectal cancer: a scoping review.', pmid: '41935608' },
        { label: 'Ismaili N, Cancer Invest, 2026, - Practice-Changing Trials in Gastrointestinal Cancers at ASCO 2025: A Critical Review and Clinical Context.', pmid: '41960736' },
        { label: 'Ciardiello et al., Ann Oncol, 2026, - Cetuximab rechallenge in molecularly selected metastatic colorectal cancer: the randomized CAVE-2 GOIM trial.', pmid: '41443411' },
        { label: 'Lee et al., NPJ Precis Oncol, 2026, - Translational feasibility of a plasmonic microarray-based liquid biopsy for KRAS codon mutation detection across tissue, plasma, and urine in early colorectal cancer.', pmid: '42069955' },
        { label: 'Ros et al., ESMO Open, 2026, - Impact of treatment discontinuation among patients with microsatellite instability or mismatch repair-deficient metastatic colorectal cancer treated with immune checkpoint inhibitors.', pmid: '42066685' },
      ],
      guidelines: 'Current evidence supports ctDNA testing for treatment de-escalation decisions in stage II CRC and prognostic stratification across stages, though specific guideline recommendations continue evolving.',
    },

    'not-in-guidelines': {
      forPatient: 'Actually, ctDNA testing for colorectal cancer is included in major guidelines. Both NCCN and ASCO have issued recommendations supporting ctDNA testing to help guide treatment decisions after surgery. NCCN recognizes ctDNA as an important risk factor, and ASCO has endorsed its use to help decide whether patients might benefit from more or less intensive chemotherapy.',
      forDoctor: 'ctDNA MRD testing is actually included in current guidelines for CRC. NCCN guidelines recognize ctDNA as a high-risk factor for recurrence in the adjuvant setting with Category 2A recommendation for stage II treatment decisions. ASCO issued a Provisional Clinical Opinion endorsing ctDNA for stage II-III CRC to identify patients who may benefit from adjuvant therapy intensification or de-escalation. Additionally, Medicare provides coverage for tumor-informed ctDNA MRD testing across solid tumors via MolDX LCD L39256.',
      stageNotes: {
        'stage-2': 'NCCN provides Category 2A recommendation for ctDNA as high-risk factor in stage II adjuvant therapy decisions, and ASCO PCO endorses ctDNA testing for treatment guidance.',
        'stage-3': 'ASCO Provisional Clinical Opinion endorses ctDNA testing for stage III CRC to guide adjuvant therapy intensification or de-escalation decisions.',
      },
      sources: [
        { label: 'NCCN, 2026, - NCCN Colon Cancer Guidelines v1.2026' },
        { label: 'ASCO, 2024, - ASCO Provisional Clinical Opinion 2024' },
        { label: 'NCCN, 2025, - NCCN Colon Cancer Guidelines v1.2025' },
        { label: 'ASCO, 2024, - ASCO PCO 2024 — CRC ctDNA' },
      ],
      guidelines: 'ctDNA MRD testing is included in both NCCN (Category 2A) and ASCO Provisional Clinical Opinion guidelines for colorectal cancer.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive ctDNA result gives your doctor important information about your cancer risk and treatment options. The DYNAMIC trial showed that doctors can safely use ctDNA results to guide treatment decisions, and the GALAXY study found that patients with positive ctDNA who received chemotherapy had much better outcomes than those who didn\'t. Your doctor can use this information to recommend the most appropriate treatment for your specific situation, potentially including chemotherapy or closer monitoring.',
      forDoctor: 'Positive ctDNA results provide actionable clinical information supported by multiple randomized trials. In stage II CRC, DYNAMIC (N=455) demonstrated safe ctDNA-guided management with non-inferior 5-year RFS (88% vs 87%) and OS (93.8% vs 93.3%, HR 1.05, P=0.887) while reducing chemotherapy use from 28% to 15% (PMID: 35657320, 40055522). GALAXY/VEGA (N>2000) showed ctDNA-positive patients receiving adjuvant chemotherapy had significantly improved DFS vs observation (HR 0.39), with ctDNA positivity conferring DFS HR 11.99 and OS HR 9.68 vs ctDNA-negative patients (PMID: 36646802). The ALTAIR trial demonstrated FTD/TPI benefit in ctDNA-positive patients across stages I-IV (median DFS 9.23 vs 5.55 months, HR 0.75, 95% CI 0.55-0.98, P=0.0406). ctDNA provides 3-10 months lead time before radiographic recurrence, enabling earlier intervention or intensified surveillance.',
      stageNotes: {
        'stage-1': 'ALTAIR trial showed benefit of FTD/TPI in ctDNA-positive stage I patients with improved DFS.',
        'stage-2': 'DYNAMIC trial demonstrated safe ctDNA-guided treatment de-escalation, reducing chemotherapy use while maintaining excellent survival outcomes.',
        'stage-3': 'Guardant Reveal showed ctDNA-positive patients had 5-year DFS of only 27.7% vs 77.1% for ctDNA-negative, with TTR HR 5.96.',
        'stage-4': 'ALTAIR trial showed FTD/TPI benefit in ctDNA-positive metastatic patients with improved DFS compared to placebo.',
      },
      sources: [
        { label: 'Tie et al., New England Journal of Medicine, 2022, - Circulating tumor DNA analysis guiding adjuvant therapy in stage II colon cancer', pmid: '35657320' },
        { label: 'Tie et al., Nature Medicine, 2025, - DYNAMIC 5-year follow-up', pmid: '40055522' },
        { label: 'Kotani et al., Nature Medicine, 2023, - GALAXY/VEGA study', pmid: '36646802' },
        { label: 'ALTAIR investigators, 2026, - ALTAIR trial' },
        { label: 'CITCCA investigators, 2026, - CITCCA study' },
        { label: 'Guardant investigators, Journal of Clinical Oncology, 2026, - Guardant Reveal stage III CRC study' },
        { label: 'Reinert et al., JAMA Oncology, 2019, - Analysis of ctDNA to Predict Outcome after Surgery and Adjuvant Treatment in Colorectal Cancer', pmid: '31070691' },
        { label: 'Jiang et al., J Gastrointest Surg, 2026, - The role of ctDNA in precision adjuvant therapy for colorectal cancer: a scoping review.', pmid: '41935608' },
        { label: 'Ismaili N, Cancer Invest, 2026, - Practice-Changing Trials in Gastrointestinal Cancers at ASCO 2025: A Critical Review and Clinical Context.', pmid: '41960736' },
        { label: 'Ciardiello et al., Ann Oncol, 2026, - Cetuximab rechallenge in molecularly selected metastatic colorectal cancer: the randomized CAVE-2 GOIM trial.', pmid: '41443411' },
        { label: 'Lee et al., NPJ Precis Oncol, 2026, - Translational feasibility of a plasmonic microarray-based liquid biopsy for KRAS codon mutation detection across tissue, plasma, and urine in early colorectal cancer.', pmid: '42069955' },
        { label: 'Ros et al., ESMO Open, 2026, - Impact of treatment discontinuation among patients with microsatellite instability or mismatch repair-deficient metastatic colorectal cancer treated with immune checkpoint inhibitors.', pmid: '42066685' },
      ],
      guidelines: 'Consider adjuvant chemotherapy for ctDNA-positive patients based on GALAXY/VEGA data showing 61% reduction in recurrence risk (HR 0.39), and evaluate clinical trials investigating treatment intensification or novel agents like FTD/TPI.',
    },

    'not-validated': {
      forPatient: 'While some MRD tests may not be specifically validated for colorectal cancer, the COSMOS trial demonstrated that ctDNA testing can achieve 98.2% accuracy in identifying true negative results and can detect cancer recurrence an average of 5.3 months before it shows up on scans. Your doctor\'s concern about validation is important because different cancer types shed DNA into the blood differently, and what works well for one cancer type may not work as well for another.',
      forDoctor: 'The COSMOS trial demonstrated 98.2% specificity for ctDNA detection with a median lead time of 5.3 months before radiographic recurrence. However, validation status varies by platform and cancer type. Key considerations include distinguishing analytical vs clinical sensitivity/specificity, landmark vs longitudinal sensitivity metrics, and the challenge that Stage II CRC presents the greatest MRD detection difficulty due to lower tumor burden despite representing cases where MRD-guided decisions have greatest impact. Serial testing with 99% analytical specificity still yields ~5% cumulative false positive probability over 5 annual tests. The Alliance N0147 phase III trial evaluating tissue-free ctDNA assay outcomes with FOLFOX-based adjuvant chemotherapy has published an erratum (Sinicrope et al., J Clin Oncol 2026, PMID: 41931716).',
      stageNotes: {
        'stage-2': 'Stage II colorectal cancers present the greatest challenge for MRD detection due to lower tumor burden and less circulating tumor DNA, yet these cases often represent where MRD-guided therapy decisions could have the most clinical impact.',
      },
      sources: [
        { label: 'COSMOS investigators, - COSMOS study' },
        { label: 'Sinicrope et al., J Clin Oncol, 2026, - Erratum: Tissue-Free Circulating Tumor DNA Assay and Patient Outcome in a Phase III Trial of FOLFOX-Based Adjuvant Chemotherapy (Alliance N0147).', pmid: '41931716' },
        { label: 'Lee et al., NPJ Precis Oncol, 2026, - Translational feasibility of a plasmonic microarray-based liquid biopsy for KRAS codon mutation detection across tissue, plasma, and urine in early colorectal cancer.', pmid: '42069955' },
      ],
      guidelines: 'MRD testing validation varies by platform and cancer type, with ongoing trials like Alliance N0147 evaluating clinical utility in colorectal cancer.',
    },

  },

  /* ═══════════════════════════════════════════
   *  BREAST — Tier 1
   * ═══════════════════════════════════════════ */
  breast: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t directly change outcomes, it provides valuable information about your risk of cancer returning and can guide treatment decisions. Studies like the DARE trial show that patients who clear ctDNA with treatment changes have much better outcomes, and the c-TRAK TN study found that ctDNA can detect cancer recurrence 6-12 months before it shows up on scans. This early detection window may allow for earlier intervention when treatments could be more effective.',
      forDoctor: 'While direct outcome modification trials are limited, emerging evidence suggests MRD testing enables actionable clinical decisions. The DARE trial demonstrated that switching ctDNA-positive HR+/HER2- patients to palbociclib+fulvestrant achieved 2-fold higher ctDNA clearance at 3 months, with 99.5% of sustained ctDNA-negative patients remaining recurrence-free at 27.4 months. The c-TRAK TN study (PMID: 36423745) showed ctDNA surveillance detects recurrence 6-12 months before radiographic progression. ABCSG-34 data with 7.1-year median follow-up demonstrates baseline ctDNA positivity significantly associates with inferior OS (HR 2.12, p=0.043, PMID: 41951687). The lead time advantage of 6-12 months creates a therapeutic window for intervention during oligometastatic disease when cure rates may be higher.',
      stageNotes: {
        'stage-i': 'Oncotype DX data shows 10.9% of high-risk patients decline recommended chemotherapy, with treatment declination associated with increased mortality risk (aHR 1.43, 95% CI 1.20-1.69).',
        'stage-ii': 'Oncotype DX data shows 10.9% of high-risk patients decline recommended chemotherapy, with treatment declination associated with increased mortality risk (aHR 1.43, 95% CI 1.20-1.69).',
      },
      sources: [
        { label: '- c-TRAK TN — ctDNA surveillance in TNBC', pmid: '36423745' },
        { label: '2025, - DARE trial — ASCO 2025 interim' },
        { label: 'Egle et al., NPJ Breast Cancer, 2026, - Long-term prognostic value of ctDNA in early breast cancer: insights from the neoadjuvant ABCSG-34 Trial.', pmid: '41951687' },
        { label: 'Ryu et al., Ann Surg Oncol, 2026, - Clinical Utility of Oncotype DX Testing in Synchronous Bilateral and Unilateral Multifocal Breast Cancer.', pmid: '41697472' },
        { label: 'Jackson et al., JCO Oncol Pract, 2026, - Chemotherapy Declination Among Patients With Early-Stage Hormone Receptor-Positive/Human Epidermal Growth Factor Receptor 2-Negative Breast Cancer and High Oncotype DX Recurrence Scores.', pmid: '42048620' },
        { label: 'Wylie et al., Sci Adv, 2026, - Pervasive enhanced transcription in inflammatory breast cancer tumors and PBMCs impacts RNA splicing and intronic RNAs in plasma.', pmid: '42066072' },
      ],
      guidelines: 'Current guidelines do not routinely recommend MRD testing outside clinical trials, though NCCN acknowledges emerging evidence for ctDNA surveillance in select high-risk patients.',
    },

    'not-in-guidelines': {
      forPatient: 'While MRD testing isn\'t yet in standard treatment guidelines for breast cancer, Medicare does cover tumor-informed ctDNA testing for solid tumors including breast cancer through their MolDX coverage policy. This means the testing is considered medically valuable enough for insurance coverage, even as research continues to define exactly how to use the results in treatment decisions.',
      forDoctor: 'Although MRD testing is not yet incorporated into standard breast cancer guidelines, Medicare provides coverage for tumor-informed ctDNA MRD testing across solid tumors via MolDX LCD L39256. This coverage decision reflects recognition of clinical utility despite the ongoing evolution of evidence-based recommendations for therapeutic decision-making based on MRD results.',
      sources: [
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'MRD testing is not currently included in standard breast cancer treatment guidelines, though Medicare provides coverage for tumor-informed ctDNA testing.',
    },

    'what-to-do-positive': {
      forPatient: 'If your ctDNA test comes back positive, your oncologist has several proven treatment options. For example, the DARE trial showed that switching to palbociclib plus fulvestrant achieved twice the rate of clearing cancer DNA from the blood compared to standard treatment. Positive ctDNA results also give your team a 6-12 month head start to detect and treat cancer recurrence before it shows up on scans, which can lead to better outcomes.',
      forDoctor: 'Positive ctDNA results provide actionable clinical information with established treatment responses. The DARE trial demonstrated that ctDNA-positive HR+/HER2- patients (60/507 screened) achieved 2-fold higher ctDNA clearance rates at 3 months when switched to palbociclib + fulvestrant. ctDNA surveillance provides a 6-12 month lead time before radiographic recurrence (c-TRAK TN; PMID: 36423745), enabling earlier therapeutic intervention. Patients achieving sustained ctDNA negativity showed excellent outcomes (99.5% recurrence-free at 27.4 months in DARE). Additionally, baseline ctDNA positivity independently predicts inferior OS (HR 2.12, p=0.043) in the ABCSG-34 trial (PMID: 41951687), supporting risk stratification and treatment intensification decisions.',
      stageNotes: {
        'stage-1': 'Early-stage patients with high-risk features may benefit from ctDNA-guided treatment decisions, as demonstrated in trials showing treatment response to targeted therapy modifications.',
        'stage-2': 'Stage II patients represent a key population where ctDNA testing can guide treatment escalation decisions, particularly given the established efficacy of CDK4/6 inhibitor combinations in ctDNA-positive cases.',
      },
      sources: [
        { label: '- c-TRAK TN — ctDNA surveillance in TNBC', pmid: '36423745' },
        { label: '2025, - DARE trial — ASCO 2025 interim' },
        { label: 'Egle et al., NPJ Breast Cancer, 2026, - Long-term prognostic value of ctDNA in early breast cancer: insights from the neoadjuvant ABCSG-34 Trial.', pmid: '41951687' },
        { label: 'Ryu et al., Ann Surg Oncol, 2026, - Clinical Utility of Oncotype DX Testing in Synchronous Bilateral and Unilateral Multifocal Breast Cancer.', pmid: '41697472' },
        { label: 'Jackson et al., JCO Oncol Pract, 2026, - Chemotherapy Declination Among Patients With Early-Stage Hormone Receptor-Positive/Human Epidermal Growth Factor Receptor 2-Negative Breast Cancer and High Oncotype DX Recurrence Scores.', pmid: '42048620' },
        { label: 'Wylie et al., Sci Adv, 2026, - Pervasive enhanced transcription in inflammatory breast cancer tumors and PBMCs impacts RNA splicing and intronic RNAs in plasma.', pmid: '42066072' },
      ],
      guidelines: 'The DARE trial provides evidence for CDK4/6 inhibitor plus fulvestrant in ctDNA-positive HR+/HER2- patients, while c-TRAK TN supports surveillance strategies for early recurrence detection.',
    },

    'not-validated': {
      forPatient: 'While ctDNA testing for breast cancer isn\'t yet validated across all subtypes, there is strong evidence supporting its use in certain situations. For triple-negative breast cancer after chemotherapy before surgery, ctDNA testing has over 95% accuracy in predicting cancer recurrence. Additionally, the Guardant Reveal test has shown 98% accuracy in breast cancer studies and can detect cancer returning about 5 months before scans would show it.',
      forDoctor: 'ctDNA testing validation in breast cancer varies by subtype and clinical context. In TNBC, post-neoadjuvant ctDNA positivity demonstrates >95% PPV for recurrence (PMID: 36423745). The Guardant Reveal assay showed 98.2% specificity with 5.3-month median lead time in the COSMOS trial. However, clinical sensitivity differs from analytical sensitivity, and landmark sensitivity is typically lower than longitudinal sensitivity. Stage II cancers present particular MRD detection challenges due to lower tumor burden, yet represent scenarios where MRD-guided decisions have greatest impact. Post-operative MRD is often near assay LOD, raising false positive risks. Consider that analytical specificity requirements become critical with serial testing - even 99% specificity yields ~5% cumulative false positive probability over 5 annual tests.',
      sources: [
        { label: '- c-TRAK TN — ctDNA surveillance in TNBC', pmid: '36423745' },
        { label: 'Wylie et al., Sci Adv, 2026, - Pervasive enhanced transcription in inflammatory breast cancer tumors and PBMCs impacts RNA splicing and intronic RNAs in plasma.', pmid: '42066072' },
      ],
      guidelines: 'ctDNA testing has strongest validation in triple-negative breast cancer post-neoadjuvant therapy, with emerging evidence across other breast cancer subtypes.',
    },

  },

  /* ═══════════════════════════════════════════
   *  LUNG (NSCLC) — Tier 1
   * ═══════════════════════════════════════════ */
  lung: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t directly change outcomes, it provides crucial information that can guide treatment decisions and help predict who will benefit most from therapy. Studies like IMpower010 show that patients with detectable ctDNA after surgery benefit significantly from immunotherapy, while those who are MRD-negative may safely avoid unnecessary treatment and its side effects. The test also detects cancer recurrence an average of 3-12 months before it shows up on scans, giving you and your doctor valuable time to adjust your treatment plan.',
      forDoctor: 'MRD testing provides actionable prognostic and predictive information that can inform treatment decisions in NSCLC. IMpower010 demonstrated that ctDNA-positive patients derive significant DFS benefit from adjuvant atezolizumab vs BSC in stage IB-IIIA NSCLC. Lei et al. (PMID: 42090629) showed MRD-positive patients have 12-fold increased recurrence risk (HR=12.0, P<0.001), while MRD-negative patients with stage IB high-risk factors showed no DFS benefit from adjuvant therapy (P=0.974). Similarly, MRD-negative EGFR-mutant patients showed no benefit from adjuvant chemotherapy (P=0.502), and MRD-negative EGFR/ALK wild-type patients showed no benefit from adjuvant immunotherapy (P=0.534). TRACERx demonstrated 164-day median lead time for relapse detection (PMID: 37055640), while a meta-analysis of 1,309 patients confirmed MRD as the strongest prognostic signal (HR=8.7). ctDNA clearance during therapy consistently correlates with improved prognosis (P<0.001).',
      stageNotes: {
        'stage-1': 'Stage IB-IIIA patients with positive ctDNA post-surgery benefit from adjuvant atezolizumab, while MRD-negative stage IB high-risk patients showed no benefit from adjuvant therapy.',
        'stage-2': 'MRD status provides 12-fold risk stratification for recurrence and can guide decisions about adjuvant therapy benefit in both EGFR-mutant and wild-type tumors.',
        'stage-3': 'Stage IB-IIIA patients with detectable ctDNA after surgery derive significant disease-free survival benefit from adjuvant immunotherapy.',
        'stage-4': 'ctDNA monitoring in advanced NSCLC shows 85% concordance with tissue profiling and provides early detection of progression in EGFR-mutant patients.',
      },
      sources: [
        { label: '- IMpower010 — ctDNA and adjuvant atezolizumab' },
        { label: '- TRACERx — ultrasensitive ctDNA in NSCLC', pmid: '37055640' },
        { label: '2025, - AEGEAN exploratory analysis — ASCO 2025' },
        { label: '2025, - DART trial — ASCO 2025' },
        { label: 'JCO Precision Oncology, 2025, - NSCLC ctDNA meta-analysis — JCO Precision Oncology 2025' },
        { label: 'Lei et al., JCO Precis Oncol, 2026, - Potential of Minimal Residual Disease in Guiding Adjuvant Therapy Decisions in Non-Small Cell Lung Cancer.', pmid: '42090629' },
        { label: 'Ranghiero et al., J Liq Biopsy, 2026, - Radiogenomic approach combining CT-based radiomics and liquid biopsy improves prognostic stratification in patients with advanced NSCLC.', pmid: '42095156' },
        { label: 'Kropf-Sanchen et al., Clin Lung Cancer, 2026, - A Retrospective, Multicenter Analysis Within the National Network Genomic Medicine Lung Cancer in Germany to Detect RET Fusions as a Possible Mechanism of Resistance in Patients With EGFR Mutations.', pmid: '42055889' },
        { label: 'Liu J et al., Expert Rev Mol Diagn, 2026, - Beyond mutations: epigenetic and fragmentomic landscapes of cfDNA in lung cancer.', pmid: '42023873' },
      ],
      guidelines: 'Current guidelines are evolving to incorporate MRD testing for treatment selection, particularly in the adjuvant setting where predictive biomarkers can help identify patients most likely to benefit from specific therapies.',
    },

    'not-in-guidelines': {
      forPatient: 'You\'re right that MRD testing isn\'t specifically recommended in the NCCN lung cancer guidelines yet, but it is recognized as an emerging tool that shows promise. The good news is that Medicare does cover this type of testing for lung cancer patients, which suggests there\'s growing acceptance of its clinical value. While we wait for formal guidelines, many oncologists are already using MRD testing to help guide treatment decisions based on the promising research results.',
      forDoctor: 'While NCCN NSCLC guidelines acknowledge ctDNA as an emerging tool, they lack specific MRD recommendations currently. However, Medicare coverage through MolDX LCD L39256 for tumor-informed ctDNA MRD testing across solid tumors, including NSCLC, indicates payer recognition of clinical utility. The absence of formal guideline recommendations doesn\'t preclude clinical use, particularly given the growing evidence base and reimbursement landscape. Many institutions are incorporating ctDNA MRD testing into clinical practice ahead of formal guideline inclusion, which typically lags behind emerging evidence.',
      sources: [
        { label: '2025, - NCCN NSCLC Guidelines v3.2025' },
      ],
      guidelines: 'NCCN recognizes ctDNA as an emerging tool for NSCLC but has not yet issued specific MRD testing recommendations.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive MRD test result gives your doctor important information about your risk of cancer coming back and helps guide treatment decisions. For example, if you test positive after surgery, studies like IMpower010 show that patients benefit significantly from immunotherapy treatment. The test can also detect cancer returning up to 5 months before it shows up on scans, allowing for earlier intervention when treatments may be more effective.',
      forDoctor: 'Positive MRD results provide actionable clinical information across multiple scenarios. In the resected setting, IMpower010 demonstrated that ctDNA-positive patients derive significant DFS benefit from adjuvant atezolizumab. MRD positivity confers a 12-fold increased recurrence risk (HR=12.0, p<0.001; PMID: 42090629) and identifies patients who benefit from intensified therapy. Conversely, MRD-negative patients showed no DFS benefit from adjuvant therapy in stage IB high-risk (p=0.974), EGFR-mutant (p=0.502), or EGFR/ALK wild-type settings (p=0.534), potentially sparing unnecessary treatment. TRACERx data show median 164-day lead time before radiologic recurrence (PMID: 37055640), enabling earlier intervention. Meta-analysis confirms MRD as the strongest prognostic factor (HR=8.70; JCO Precision Oncology 2025). In advanced disease, 85% tissue-ctDNA concordance supports treatment selection when tissue unavailable (PMID: 42095156).',
      stageNotes: {
        'stage-1': 'Stage IB MRD-negative patients with high-risk factors showed no DFS benefit from adjuvant therapy (p=0.974), while MRD-positive patients had 12-fold increased recurrence risk requiring intensified treatment.',
        'stage-2': 'Stage II patients with positive MRD have significantly worse outcomes (HR=12.0, p<0.001) and may benefit from treatment intensification, while MRD-negative patients show no benefit from standard adjuvant approaches.',
        'stage-3': 'Stage IB-IIIA ctDNA-positive patients demonstrated significant DFS improvement with adjuvant atezolizumab in IMpower010, while stage III patients in AEGEAN had worse outcomes without ctDNA clearance during perioperative durvalumab.',
        'stage-4': 'Advanced NSCLC patients show 85% tissue-ctDNA concordance for molecular profiling, with baseline ctDNA detection predicting higher progression risk in EGFR-mutant disease (p=0.018).',
      },
      sources: [
        { label: '- IMpower010 — ctDNA and adjuvant atezolizumab' },
        { label: '- TRACERx — ultrasensitive ctDNA in NSCLC', pmid: '37055640' },
        { label: '2025, - AEGEAN exploratory analysis — ASCO 2025' },
        { label: '2025, - DART trial — ASCO 2025' },
        { label: 'JCO Precision Oncology, 2025, - NSCLC ctDNA meta-analysis — JCO Precision Oncology 2025' },
        { label: 'Lei et al., JCO Precis Oncol, 2026, - Potential of Minimal Residual Disease in Guiding Adjuvant Therapy Decisions in Non-Small Cell Lung Cancer.', pmid: '42090629' },
        { label: 'Ranghiero et al., J Liq Biopsy, 2026, - Radiogenomic approach combining CT-based radiomics and liquid biopsy improves prognostic stratification in patients with advanced NSCLC.', pmid: '42095156' },
        { label: 'Kropf-Sanchen et al., Clin Lung Cancer, 2026, - A Retrospective, Multicenter Analysis Within the National Network Genomic Medicine Lung Cancer in Germany to Detect RET Fusions as a Possible Mechanism of Resistance in Patients With EGFR Mutations.', pmid: '42055889' },
        { label: 'Liu J et al., Expert Rev Mol Diagn, 2026, - Beyond mutations: epigenetic and fragmentomic landscapes of cfDNA in lung cancer.', pmid: '42023873' },
      ],
      guidelines: 'IMpower010 supports adjuvant atezolizumab in ctDNA-positive stage IB-IIIA NSCLC, while AEGEAN and DART trials inform perioperative and consolidative immunotherapy decisions based on MRD status.',
    },

    'not-validated': {
      forPatient: 'While your doctor is right that MRD testing for lung cancer is still being studied, there is growing evidence that these tests work well for lung cancer patients. Recent studies like TRACERx and COSMOS have shown that newer MRD tests can detect very small amounts of cancer DNA in blood samples from lung cancer patients, with high accuracy rates. The Guardant Reveal test, for example, showed 98% accuracy in the COSMOS study and could detect cancer recurrence about 5 months before it would show up on scans.',
      forDoctor: 'While comprehensive validation is ongoing, substantial evidence supports MRD testing utility in NSCLC. The TRACERx study (PMID: 37055640) demonstrated PhasED-Seq achieved superior performance versus CAPP-Seq with LOD95 of 1 ppm vs 84 ppm and clinical sensitivity of 67% vs 28% (P=0.022). Lei et al. enrolled 165 stage IA-IIIB NSCLC patients post-R0 resection for MRD analysis (PMID: 42090629). Mutation concordance studies show 91% EGFR concordance (κ=0.79) and 99% KRAS concordance (κ=0.97) between tissue and ctDNA (PMID: 42095156). Guardant Reveal demonstrated 98.2% specificity with 5.3-month median lead time in COSMOS. Key considerations include distinguishing clinical vs analytical sensitivity, stage-dependent detection challenges (particularly stage II), and cumulative false positive risk with serial testing (≈5% over 5 annual tests at 99% specificity).',
      stageNotes: {
        'stage-1': 'Stage I NSCLC patients were included in a 165-patient MRD study examining post-surgical blood samples collected before adjuvant therapy initiation.',
        'stage-2': 'Stage II NSCLC patients face the greatest MRD detection challenge due to lower tumor burden but represent where MRD-guided therapy decisions often have the most clinical impact.',
        'stage-3': 'Stage III NSCLC patients through IIIB were included in recent MRD validation studies with blood sampling protocols established for post-R0 resection monitoring.',
        'stage-4': 'Stage IV NSCLC shows excellent tissue-ctDNA concordance for actionable mutations, with 91% EGFR and 99% KRAS concordance rates supporting ctDNA utility.',
      },
      sources: [
        { label: '- TRACERx — ultrasensitive ctDNA in NSCLC', pmid: '37055640' },
        { label: 'Lei et al., JCO Precis Oncol, 2026, - Potential of Minimal Residual Disease in Guiding Adjuvant Therapy Decisions in Non-Small Cell Lung Cancer.', pmid: '42090629' },
        { label: 'Ranghiero et al., J Liq Biopsy, 2026, - Radiogenomic approach combining CT-based radiomics and liquid biopsy improves prognostic stratification in patients with advanced NSCLC.', pmid: '42095156' },
        { label: 'Liu J et al., Expert Rev Mol Diagn, 2026, - Beyond mutations: epigenetic and fragmentomic landscapes of cfDNA in lung cancer.', pmid: '42023873' },
      ],
      guidelines: 'MRD testing in lung cancer lacks comprehensive guideline validation but shows robust evidence across multiple studies and platforms.',
    },

  },

  /* ═══════════════════════════════════════════
   *  BLADDER — Tier 2
   * ═══════════════════════════════════════════ */
  bladder: {
    'no-evidence': {
      forPatient: 'Recent evidence from the IMvigor011 trial published in the New England Journal of Medicine actually shows that MRD testing can guide treatment decisions that improve outcomes in bladder cancer. When patients tested positive for ctDNA after surgery, those who received immunotherapy had significantly longer survival - living a median of 33 months compared to 21 months for those who didn\'t receive treatment. This was the first major trial to prove that acting on MRD results can actually help patients live longer.',
      forDoctor: 'The IMvigor011 Phase III trial (NEJM 2024, PMID: 41124204) provides Level 1 evidence that MRD-guided intervention improves outcomes in bladder cancer. Among 250 ctDNA+ patients randomized to adjuvant atezolizumab vs placebo, treatment significantly improved DFS (HR 0.64, p=0.0047; median 9.9 vs 4.8 months) and OS (median 32.8 vs 21.1 months). Twelve-month outcomes favored atezolizumab: DFS 44.7% vs 30.0% and OS 85.1% vs 70.0%. Conversely, ctDNA-negative patients (n=511) had excellent outcomes with observation alone: 12-month DFS 95.4% and OS 100%. This represents the first randomized trial demonstrating that ctDNA-guided therapeutic intervention improves clinical outcomes in any adjuvant cancer setting.',
      stageNotes: {
        'stage-2': 'IMvigor011 trial data demonstrates that ctDNA-guided adjuvant atezolizumab significantly improves both disease-free and overall survival in ctDNA-positive patients.',
        'stage-3': 'IMvigor011 trial data demonstrates that ctDNA-guided adjuvant atezolizumab significantly improves both disease-free and overall survival in ctDNA-positive patients.',
      },
      sources: [
        { label: 'Powles et al., NEJM, 2024, - IMvigor011', pmid: '41124204' },
      ],
      guidelines: 'The IMvigor011 results represent the first Level 1 evidence for MRD-guided intervention in any cancer type and are likely to influence future treatment guidelines for bladder cancer.',
    },

    'not-in-guidelines': {
      forPatient: 'While ctDNA testing for bladder cancer isn\'t yet in formal treatment guidelines, Medicare does cover this testing for solid tumors including bladder cancer, recognizing its clinical value. This coverage suggests the medical community sees real benefit in using ctDNA to monitor for cancer recurrence. Your oncologist might consider this testing to help detect any remaining cancer cells after treatment, even without formal guideline recommendations.',
      forDoctor: 'Although ctDNA MRD testing lacks formal inclusion in bladder cancer guidelines, Medicare coverage through MolDX LCD L39256 provides reimbursement for tumor-informed ctDNA across solid tumors, including bladder cancer. This coverage decision reflects CMS recognition of clinical utility despite the absence of guideline recommendations. Given the aggressive nature of muscle-invasive bladder cancer and high recurrence rates, ctDNA monitoring may offer valuable surveillance capabilities for treatment response assessment and early recurrence detection, particularly in the adjuvant setting where clinical decision-making could be informed by MRD status.',
      sources: [
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'ctDNA testing is not currently included in major bladder cancer treatment guidelines, though Medicare provides coverage for solid tumor ctDNA testing.',
    },

    'what-to-do-positive': {
      forPatient: 'If your ctDNA test is positive after treatment, your doctor now has a proven treatment option. The IMvigor011 trial showed that patients with positive ctDNA who received the immunotherapy atezolizumab lived longer without their cancer returning (about 10 months versus 5 months) and had better overall survival. This gives your oncologist clear evidence for taking action rather than just waiting and watching.',
      forDoctor: 'The IMvigor011 Phase III trial (PMID: 41124204) provides Level 1 evidence for intervention in ctDNA-positive bladder cancer patients. In 250 ctDNA+ patients randomized 2:1 to adjuvant atezolizumab vs placebo, treatment significantly improved DFS (median 9.9 vs 4.8 months; HR 0.64, P=0.0047) and OS (median 32.8 vs 21.1 months). Twelve-month DFS was 44.7% vs 30.0% and 12-month OS was 85.1% vs 70.0% for atezolizumab vs placebo, respectively. This represents the first randomized controlled trial demonstrating survival benefit from ctDNA-guided adjuvant therapy in any cancer type.',
      stageNotes: {
        'stage-ii': 'IMvigor011 trial data supports adjuvant atezolizumab for ctDNA-positive patients with significant DFS and OS benefits.',
        'stage-iii': 'IMvigor011 trial data supports adjuvant atezolizumab for ctDNA-positive patients with significant DFS and OS benefits.',
      },
      sources: [
        { label: 'Powles et al., NEJM, 2024, - IMvigor011', pmid: '41124204' },
      ],
      guidelines: 'IMvigor011 provides Level 1 evidence for adjuvant atezolizumab in ctDNA-positive bladder cancer patients following curative-intent treatment.',
    },

    'not-validated': {
      forPatient: 'Your doctor is right that MRD testing hasn\'t been specifically validated in large bladder cancer studies yet. While MRD tests like Guardant Reveal have shown promise in other cancer types with high accuracy (over 98% specificity in the COSMOS trial), each cancer type behaves differently and needs its own validation studies. You might ask your doctor about participating in research studies or whether the test could still provide useful information as part of your overall care plan.',
      forDoctor: 'MRD testing in bladder cancer lacks robust validation data compared to other tumor types. While tumor-informed ctDNA assays achieve LODs near 0.01% VAF (PMID: 41789684) and Guardant Reveal demonstrated 98.2% specificity with 5.3-month median lead time in COSMOS, these data derive primarily from other cancer types. Clinical sensitivity varies significantly from analytical sensitivity, and landmark vs. longitudinal sensitivity metrics should be distinguished when counseling patients. Given the lack of bladder-specific validation studies, consider discussing research trial participation or off-label use with appropriate patient counseling regarding performance limitations.',
      stageNotes: {
        'stage-2': 'Stage II bladder cancers present particular MRD detection challenges due to lower tumor burden and reduced circulating tumor DNA, despite representing cases where MRD-guided therapy decisions could have the most clinical impact.',
      },
      sources: [
        { label: 'Guardant Health, - COSMOS specificity' },
        { label: 'Guardant Health, - COSMOS lead time' },
        { label: 'MR, 2024, - OpenOnco Expert Advisory Panel' },
        { label: 'Feng L et al., Cancer Treat Res Commun, 2026, - Multimodal liquid biopsy surveillance after pancreatectomy for pancreatic ductal adenocarcinoma: evidence and a confirmation&#x2011;gated, trial&#x2011;ready framework.', pmid: '42092284' },
        { label: 'Erul et al., Expert Rev Mol Diagn, 2026, - Liquid biopsy for biliary tract cancer: available evidence and future research directions.', pmid: '42087549' },
        { label: 'Galot R et al., Curr Opin Oncol, 2026, - Circulating tumor DNA in human papilloma virus negative head and neck squamous cell carcinoma.', pmid: '41789684' },
        { label: 'Vedeld et al., JHEP Rep, 2026, - Accurate detection of cholangiocarcinoma in primary sclerosing cholangitis by DNA methylation biomarkers in bile and plasma.', pmid: '42067191' },
        { label: 'Currie et al., J Mol Diagn, 2026, - Validation of MyHPVscore: a high-performance HPV ctDNA lab developed test.', pmid: '42092730' },
        { label: 'Michalski et al., JMIR Res Protoc, 2026, - Liquid Biopsy Biomarkers in Patients With Metastatic Castration-Resistant Prostate Cancer Receiving Prostate-Specific Membrane Antigen Radioligand Therapy: Protocol for a Prospective, Longitudinal Multicenter Observational Study.', pmid: '42054640' },
        { label: 'Caserta et al., Eur J Haematol, 2026, - Minimal Residual Disease as a Biological Trait: Rethinking Disease Persistence in Hematologic Malignancies.', pmid: '42036772' },
      ],
      guidelines: 'Current guidelines do not include validated MRD testing recommendations for bladder cancer due to insufficient cancer-specific validation studies.',
    },

  },

  /* ═══════════════════════════════════════════
   *  MELANOMA — Tier 2
   * ═══════════════════════════════════════════ */
  melanoma: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t directly change outcomes, it provides valuable information about your cancer risk that can guide treatment decisions. The COMBI-AD study showed that melanoma patients with detectable circulating tumor DNA had nearly three times higher risk of cancer returning, regardless of whether they received targeted therapy or placebo. This information can help you and your doctor make more informed decisions about follow-up care and potential additional treatments.',
      forDoctor: 'MRD testing in melanoma provides prognostic information that can inform clinical decision-making. The COMBI-AD biomarker analysis (N=597 stage III melanoma patients, 60-month follow-up) demonstrated that ctDNA+ patients had significantly increased recurrence risk in both placebo (HR 2.91, p<0.0001) and targeted therapy arms (HR 2.98, p<0.0001) (PMID: 40250457). In metastatic disease, ctDNA dynamics correlate with outcomes - 6-month ctDNA clearance (47.4% rate) was associated with improved PFS (HR 10.0, p=0.03) during adjuvant immunotherapy (PMID: 39169411). ctDNA detection provides 3-12 months lead time before radiographic recurrence (PMID: 31070691). While direct outcome modification trials are pending, the strong prognostic value can guide surveillance intensity and inform treatment discussions.',
      stageNotes: {
        'stage-3': 'COMBI-AD data shows ctDNA+ stage III patients have ~3-fold higher recurrence risk regardless of targeted therapy use.',
        'stage-4': 'ctDNA clearance at 6 months during immunotherapy correlates with improved progression-free survival.',
      },
      sources: [
        { label: 'COMBI-AD investigators et al., Lancet Oncology, 2026, - COMBI-AD biomarker analysis', pmid: '40250457' },
        { label: 'Lee et al., - ctDNA in resected melanoma', pmid: '39169411' },
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'Current guidelines recognize MRD testing as investigational, with Medicare coverage available through MolDX for tumor-informed ctDNA assays.',
    },

    'not-in-guidelines': {
      forPatient: 'While ctDNA testing isn\'t included in the official melanoma treatment guidelines yet, this doesn\'t mean it\'s not useful - guidelines often take time to catch up with new technologies. Medicare does cover this type of testing for melanoma patients, which suggests there\'s recognized value in the information it provides. You might ask your doctor about whether ctDNA testing could help inform your specific treatment decisions, even if it\'s not yet in the standard guidelines.',
      forDoctor: 'While NCCN Melanoma guidelines currently lack ctDNA MRD recommendations, this reflects the typical lag between emerging evidence and formal guideline incorporation rather than lack of clinical utility. Medicare coverage through MolDX LCD L39256 for tumor-informed ctDNA MRD testing across solid tumors, including melanoma, provides reimbursement support. Consider discussing ctDNA MRD testing as an adjunctive tool for treatment monitoring and recurrence detection, particularly in high-risk patients where the information could influence clinical decision-making regarding adjuvant therapy duration or surveillance intensity.',
      sources: [
        { label: 'NCCN, 2025, - NCCN Melanoma Guidelines v2.2025' },
      ],
      guidelines: 'NCCN Melanoma guidelines do not currently include ctDNA MRD testing recommendations, though Medicare provides coverage through MolDX.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive MRD result in melanoma helps your doctor understand your risk for cancer coming back and guides important treatment decisions. The COMBI-AD study showed that patients with detectable circulating tumor DNA had nearly 3 times higher risk of recurrence, whether they received targeted therapy or not. Your doctor can use this information to discuss more intensive monitoring, additional treatments, or clinical trial options that might benefit high-risk patients.',
      forDoctor: 'Positive ctDNA results in melanoma provide actionable clinical information for risk stratification and treatment planning. The COMBI-AD biomarker analysis (n=597, 60-month follow-up) demonstrated that ctDNA+ patients had significantly increased recurrence risk in both placebo (HR 2.91, p=0.0001) and targeted therapy arms (HR 2.98, p=0.0001) (PMID: 40250457). This 3-12 month lead time before radiographic recurrence enables earlier intervention discussions, intensified surveillance protocols, clinical trial enrollment for high-risk patients, and informed shared decision-making regarding adjuvant therapy duration or escalation. Medicare coverage is available through MolDX for tumor-informed ctDNA assays.',
      stageNotes: {
        'stage-3': 'Stage III melanoma patients with positive ctDNA have nearly 3-fold increased recurrence risk regardless of adjuvant targeted therapy based on COMBI-AD data.',
        'stage-4': 'In advanced melanoma, 6-month ctDNA clearance during treatment is associated with significantly improved progression-free survival.',
      },
      sources: [
        { label: 'COMBI-AD investigators et al., Lancet Oncology, 2026, - COMBI-AD biomarker analysis', pmid: '40250457' },
        { label: 'Lee et al., - ctDNA in resected melanoma', pmid: '39169411' },
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'COMBI-AD provides the primary evidence base for ctDNA interpretation in stage III melanoma, with Medicare coverage available through MolDX pathways.',
    },

    'not-validated': {
      forPatient: 'While MRD testing isn\'t formally validated specifically for melanoma, there is emerging research showing it can detect circulating tumor DNA in melanoma patients. The detection rates vary significantly by stage - only about 13% of stage III patients have detectable ctDNA after surgery, while over 90% of stage IV patients test positive. Your oncologist may be concerned about the lower detection rates in earlier-stage disease and the lack of large validation studies specifically in melanoma.',
      forDoctor: 'MRD testing in melanoma lacks formal validation but emerging data shows feasibility. The COMBI-AD study (N=597) demonstrated only 13% baseline ctDNA detection in stage III melanoma (PMID: 40250457), while stage IV patients show 91.7% pre-ICI ctDNA positivity (PMID: 39169411). The low detection rate in stage III reflects melanoma\'s relatively low tumor burden compared to other solid tumors. Commercial platforms like Guardant Reveal show 98.2% specificity and 5.3-month median lead time in pan-cancer studies, but melanoma-specific clinical utility data remains limited. Consider tissue-informed approaches for higher analytical sensitivity in this low-shedding tumor type.',
      stageNotes: {
        'stage-3': 'Stage III melanoma shows relatively low ctDNA detection rates at only 13% in the COMBI-AD study, which may limit MRD testing utility.',
        'stage-4': 'Stage IV melanoma demonstrates high ctDNA detection rates at 91.7% before immunotherapy, suggesting MRD testing may be more informative in metastatic disease.',
      },
      sources: [
        { label: 'COMBI-AD investigators et al., Lancet Oncology, 2026, - COMBI-AD biomarker analysis', pmid: '40250457' },
        { label: 'Lee et al., - ctDNA in resected melanoma', pmid: '39169411' },
      ],
      guidelines: 'MRD testing for melanoma currently lacks formal validation and is not included in standard clinical guidelines.',
    },

  },

  /* ═══════════════════════════════════════════
   *  DEFAULT — Tier 3 (generic fallback)
   * ═══════════════════════════════════════════ */
  _default: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t yet have proven treatments that improve survival when positive, it provides valuable information about your cancer risk. Studies show MRD can detect cancer recurrence 3-12 months before scans, and patients with positive MRD tests have much higher rates of cancer coming back. This early warning can help you and your doctor make more informed decisions about follow-up care and potential treatments.',
      forDoctor: 'Emerging evidence demonstrates MRD\'s prognostic value across solid tumors. The preSINO trial (n=93 ESCC patients) showed MRD positivity was an independent predictor of recurrence-free survival (HR 13.62, p<0.001) with 1-year recurrence rates of 6.1% vs 66.7% for MRD-negative vs MRD-positive patients (PMID: 42086163). ctDNA detection provides 3-12 month lead time over radiographic recurrence (Reinert et al., JAMA Oncol 2019, PMID: 31070691). While therapeutic interventions based on MRD status lack definitive outcome data, the strong prognostic stratification supports its utility for risk assessment, surveillance planning, and patient counseling. Combined with pathologic response, MRD creates distinct risk subgroups (3.7-82.4% 1-year recurrence rates, p<0.001).',
      sources: [
        { label: 'Reinert et al., JAMA Oncology, 2019, - lead time', pmid: '31070691' },
        { label: 'Yumashev et al., Clin Transl Oncol, 2026, - Circulating tumor DNA-based detection of molecular residual disease in isocitrate dehydrogenase-mutant cholangiocarcinoma for biomarker-guided therapy.', pmid: '41912863' },
        { label: 'Liu et al., J Thorac Cardiovasc Surg, 2026, - Postoperative MRD status Refines Recurrence Risk Stratification Beyond Pathologic Response After Neoadjuvant Chemoradiotherapy for ESCC.', pmid: '42086163' },
        { label: 'Unknown, Cancer Discov, 2026, - More Questions Than Answers in Trial of GRAIL\'s Galleri.', pmid: '41817436' },
        { label: 'Galot R et al., Curr Opin Oncol, 2026, - Circulating tumor DNA in human papilloma virus negative head and neck squamous cell carcinoma.', pmid: '41789684' },
        { label: 'Michalski et al., JMIR Res Protoc, 2026, - Liquid Biopsy Biomarkers in Patients With Metastatic Castration-Resistant Prostate Cancer Receiving Prostate-Specific Membrane Antigen Radioligand Therapy: Protocol for a Prospective, Longitudinal Multicenter Observational Study.', pmid: '42054640' },
      ],
      guidelines: 'Current guidelines do not universally recommend MRD testing, though NCCN and other organizations acknowledge its emerging prognostic value in select solid tumor settings.',
    },

    'not-in-guidelines': {
      forPatient: 'While MRD testing isn\'t yet included in formal cancer treatment guidelines, Medicare has recognized its clinical value and now covers tumor-informed ctDNA testing for solid tumors. This coverage decision reflects growing evidence that this testing can provide important information about your cancer treatment. Your doctor\'s concern about guidelines is understandable, but the Medicare coverage suggests the medical community is moving toward broader acceptance of this technology.',
      forDoctor: 'Although MRD testing is not yet incorporated into major oncology guidelines, Medicare\'s MolDX Local Coverage Determination L39256 provides coverage for tumor-informed ctDNA MRD testing across solid tumors. This coverage decision by CMS indicates recognition of the clinical utility of MRD testing, even in the absence of formal guideline recommendations. The Medicare coverage may facilitate patient access while awaiting formal guideline incorporation, which typically lags behind emerging evidence and clinical adoption.',
      sources: [
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'MRD testing is not yet included in major oncology guidelines, though Medicare coverage suggests evolving clinical acceptance.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive MRD test gives your doctor valuable information to guide your care. It identifies you as being at higher risk for cancer returning, often 3-12 months before it would show up on scans. This early warning allows your doctor to monitor you more closely and potentially consider additional treatments or clinical trials that might help prevent recurrence.',
      forDoctor: 'MRD positivity provides actionable clinical information for risk stratification and treatment planning. Studies demonstrate 3-12 month lead time from ctDNA detection to radiographic recurrence (PMID: 31070691). The preSINO trial showed MRD positivity was an independent predictor of recurrence with HR 13.62 (p<0.001), stratifying 1-year recurrence rates from 6.1% (MRD-negative) to 66.7% (MRD-positive) (PMID: 42086163). Positive results warrant intensified surveillance protocols, consideration for adjuvant therapy escalation, and enrollment in clinical trials investigating MRD-directed interventions. Combined with pathologic response, MRD status can further stratify patients into four distinct risk groups with 1-year recurrence rates ranging from 3.7% to 82.4% (p<0.001).',
      sources: [
        { label: 'Reinert et al., JAMA Oncology, 2019, - lead time', pmid: '31070691' },
        { label: 'Yumashev et al., Clin Transl Oncol, 2026, - Circulating tumor DNA-based detection of molecular residual disease in isocitrate dehydrogenase-mutant cholangiocarcinoma for biomarker-guided therapy.', pmid: '41912863' },
        { label: 'Liu et al., J Thorac Cardiovasc Surg, 2026, - Postoperative MRD status Refines Recurrence Risk Stratification Beyond Pathologic Response After Neoadjuvant Chemoradiotherapy for ESCC.', pmid: '42086163' },
        { label: 'Unknown, Cancer Discov, 2026, - More Questions Than Answers in Trial of GRAIL\'s Galleri.', pmid: '41817436' },
        { label: 'Galot R et al., Curr Opin Oncol, 2026, - Circulating tumor DNA in human papilloma virus negative head and neck squamous cell carcinoma.', pmid: '41789684' },
        { label: 'Michalski et al., JMIR Res Protoc, 2026, - Liquid Biopsy Biomarkers in Patients With Metastatic Castration-Resistant Prostate Cancer Receiving Prostate-Specific Membrane Antigen Radioligand Therapy: Protocol for a Prospective, Longitudinal Multicenter Observational Study.', pmid: '42054640' },
      ],
      guidelines: 'Consider intensified surveillance, adjuvant therapy escalation, or enrollment in MRD-directed clinical trials for positive results.',
    },

    'not-validated': {
      forPatient: 'Your doctor is right that MRD tests aren\'t specifically validated for every cancer type, but the technology itself has shown promising results across many solid tumors. The COSMOS trial demonstrated that MRD testing can detect cancer recurrence about 5 months before it shows up on scans, with very high accuracy (98.2% specificity). While validation studies are ongoing for different cancer types, the fundamental ability to detect circulating tumor DNA applies broadly across solid tumors.',
      forDoctor: 'While cancer-type specific validation remains limited, ctDNA-based MRD testing demonstrates consistent technical performance across solid tumors. The Guardant Reveal COSMOS study showed 98.2% specificity with 5.3-month median lead time over imaging recurrence. Tumor-informed assays achieve LODs near 0.01% VAF, with detection rates varying by cancer type (HNSCC ~80% localized, >90% metastatic; PMID: 41789684). Clinical sensitivity differs significantly from analytical sensitivity and varies by stage, timepoint (landmark vs longitudinal), and use case (adjuvant decision-making vs surveillance). Serial testing compounds false positive risk even with high specificity (5% cumulative FP probability over 5 tests at 99% specificity). Stage II tumors present the greatest detection challenge due to lower ctDNA shedding but represent the highest clinical utility for adjuvant decisions.',
      stageNotes: {
        'stage-2': 'Stage II cancers present the greatest MRD detection challenge due to lower tumor burden and less circulating tumor DNA, yet represent where MRD-guided therapy decisions often have the most impact.',
      },
      sources: [
        { label: 'Guardant Health, - COSMOS specificity' },
        { label: 'Guardant Health, - COSMOS lead time' },
        { label: 'MR, 2024, - OpenOnco Expert Advisory Panel' },
        { label: 'Feng L et al., Cancer Treat Res Commun, 2026, - Multimodal liquid biopsy surveillance after pancreatectomy for pancreatic ductal adenocarcinoma: evidence and a confirmation&#x2011;gated, trial&#x2011;ready framework.', pmid: '42092284' },
        { label: 'Erul et al., Expert Rev Mol Diagn, 2026, - Liquid biopsy for biliary tract cancer: available evidence and future research directions.', pmid: '42087549' },
        { label: 'Galot R et al., Curr Opin Oncol, 2026, - Circulating tumor DNA in human papilloma virus negative head and neck squamous cell carcinoma.', pmid: '41789684' },
        { label: 'Vedeld et al., JHEP Rep, 2026, - Accurate detection of cholangiocarcinoma in primary sclerosing cholangitis by DNA methylation biomarkers in bile and plasma.', pmid: '42067191' },
        { label: 'Currie et al., J Mol Diagn, 2026, - Validation of MyHPVscore: a high-performance HPV ctDNA lab developed test.', pmid: '42092730' },
        { label: 'Michalski et al., JMIR Res Protoc, 2026, - Liquid Biopsy Biomarkers in Patients With Metastatic Castration-Resistant Prostate Cancer Receiving Prostate-Specific Membrane Antigen Radioligand Therapy: Protocol for a Prospective, Longitudinal Multicenter Observational Study.', pmid: '42054640' },
        { label: 'Caserta et al., Eur J Haematol, 2026, - Minimal Residual Disease as a Biological Trait: Rethinking Disease Persistence in Hematologic Malignancies.', pmid: '42036772' },
      ],
      guidelines: 'Cancer-type specific validation studies are ongoing, with broader technical validation established across solid tumor platforms.',
    },

  },
};
