/**
 * Physician FAQ — Personalized answers for patient advocacy
 *
 * Structure: PHYSICIAN_FAQ_DATA[cancerType][concernId] = { ... }
 *
 * Cancer type tiers:
 *   Tier 1 (full): colorectal, breast, lung
 *   Tier 2 (moderate): bladder, melanoma
 *   Tier 3 (generic): everything else uses '_default'
 *
 * Stage-specific notes are optional overlays on the base answer.
 *
 * Generated by: node evidence/scripts/render-faq.js
 * Last rendered: 2026-04-13
 */

export const CONCERNS = [
  { id: 'no-evidence', label: '"There\'s no evidence MRD results change outcomes."' },
  { id: 'not-in-guidelines', label: '"It\'s not in the guidelines yet."' },
  { id: 'what-to-do-positive', label: '"What would I even do with a positive result?"' },
  { id: 'insurance', label: '"Insurance won\'t cover it."', isWizardLink: true },
  { id: 'not-validated', label: '"The test isn\'t validated for your cancer type."' },
];

// Helper to get the best answer for a cancer type, falling back to _default
export function getAnswer(cancerType, concernId) {
  const typeData = PHYSICIAN_FAQ_DATA[cancerType] || PHYSICIAN_FAQ_DATA['_default'];
  return typeData[concernId] || PHYSICIAN_FAQ_DATA['_default'][concernId];
}

// Helper to get stage-specific note
export function getStageNote(cancerType, concernId, stage) {
  const answer = getAnswer(cancerType, concernId);
  if (!answer?.stageNotes || !stage) return null;
  return answer.stageNotes[stage] || null;
}

export const PHYSICIAN_FAQ_DATA = {

  /* ═══════════════════════════════════════════
   *  COLORECTAL — Tier 1 (strongest evidence)
   * ═══════════════════════════════════════════ */
  colorectal: {
    'no-evidence': {
      forPatient: 'While MRD testing hasn\'t yet shown direct survival improvements, the DYNAMIC trial demonstrated that ctDNA-guided treatment decisions can safely reduce chemotherapy use by nearly half in stage II patients without compromising outcomes. Multiple large studies show that ctDNA testing provides valuable prognostic information, identifying high-risk patients who may benefit from closer monitoring or alternative treatments. The test can detect cancer recurrence months before it shows up on scans, giving you and your doctor more time to make informed decisions about your care.',
      forDoctor: 'The DYNAMIC trial (N=455) demonstrated non-inferiority of ctDNA-guided vs. standard management in stage II CRC with 5-year RFS 88% vs. 87% and OS 93.8% vs. 93.3% (HR 1.05, P=0.887), while reducing adjuvant chemotherapy use from 28% to 15% (PMID: 35657320, 40055522). GALAXY/VEGA (N>2,000) showed ctDNA+ patients had dramatically worse outcomes (DFS HR 11.99, OS HR 9.68) but benefited significantly from adjuvant chemotherapy vs. observation (HR 0.39) (PMID: 36646802). The ALTAIR trial demonstrated treatment benefit in ctDNA+ patients with FTD/TPI vs. placebo (median DFS 9.23 vs. 5.55 months, HR 0.75, 95% CI 0.55-0.98, P=0.0406). While escalation strategies haven\'t shown definitive DFS gains, ctDNA provides 3-10 month lead time for recurrence detection and enables risk-stratified management decisions.',
      stageNotes: {
        'stage-1': 'ALTAIR trial included stage I patients showing treatment benefit with FTD/TPI in ctDNA-positive cases (HR 0.75, P=0.0406).',
        'stage-2': 'DYNAMIC trial specifically in stage II patients demonstrated safe reduction of adjuvant chemotherapy from 28% to 15% without compromising 5-year outcomes.',
        'stage-3': 'Guardant Reveal study showed ctDNA+ stage III patients had 5-year DFS of only 27.7% vs. 77.1% for ctDNA- patients, with TTR HR 5.96.',
        'stage-4': 'ALTAIR trial showed treatment benefit with FTD/TPI vs. placebo in ctDNA-positive metastatic patients (median DFS 9.23 vs. 5.55 months).',
      },
      sources: [
        { label: 'Tie et al., New England Journal of Medicine, 2022, - Circulating tumor DNA analysis guiding adjuvant therapy in stage II colon cancer', pmid: '35657320' },
        { label: 'Tie et al., Nature Medicine, 2025, - DYNAMIC 5-year follow-up', pmid: '40055522' },
        { label: 'Kotani et al., Nature Medicine, 2023, - GALAXY/VEGA study', pmid: '36646802' },
        { label: 'ALTAIR investigators, 2026, - ALTAIR trial' },
        { label: 'CITCCA investigators, 2026, - CITCCA study' },
        { label: 'Guardant investigators, Journal of Clinical Oncology, 2026, - Guardant Reveal stage III CRC study' },
        { label: 'Reinert et al., JAMA Oncology, 2019, - Analysis of ctDNA to Predict Outcome after Surgery and Adjuvant Treatment in Colorectal Cancer', pmid: '31070691' },
        { label: 'Jiang et al., J Gastrointest Surg, 2026, - The role of ctDNA in precision adjuvant therapy for colorectal cancer: a scoping review.', pmid: '41935608' },
        { label: 'Ismaili N, Cancer Invest, 2026, - Practice-Changing Trials in Gastrointestinal Cancers at ASCO 2025: A Critical Review and Clinical Context.', pmid: '41960736' },
      ],
      guidelines: 'Current evidence supports ctDNA-guided de-escalation in stage II colon cancer, though guidelines are evolving as escalation strategies remain investigational.',
    },

    'not-in-guidelines': {
      forPatient: 'Actually, ctDNA testing for colorectal cancer is included in current guidelines. Both NCCN and ASCO have endorsed ctDNA testing to help guide treatment decisions after surgery. NCCN recognizes ctDNA as an important factor for identifying patients at high risk for cancer coming back, and ASCO issued guidance supporting its use to help decide whether to intensify or reduce chemotherapy treatment.',
      forDoctor: 'ctDNA MRD testing is actually supported by current guidelines for CRC. NCCN recognizes ctDNA as a high-risk factor for recurrence in the adjuvant setting with Category 2A recommendation for stage II adjuvant therapy decisions. ASCO issued a Provisional Clinical Opinion endorsing ctDNA for stage II-III CRC to identify patients who may benefit from adjuvant therapy intensification or de-escalation. Additionally, Medicare provides coverage for tumor-informed ctDNA MRD testing across solid tumors via MolDX LCD L39256.',
      stageNotes: {
        'stage-2': 'NCCN provides Category 2A recommendation for ctDNA as high-risk factor in stage II adjuvant therapy decisions, and ASCO PCO endorses testing for treatment intensification or de-escalation.',
        'stage-3': 'ASCO PCO endorses ctDNA testing for stage III CRC to guide adjuvant therapy intensification or de-escalation decisions.',
      },
      sources: [
        { label: 'NCCN, 2026, - NCCN Colon Cancer Guidelines v1.2026' },
        { label: 'ASCO, 2024, - ASCO Provisional Clinical Opinion 2024' },
        { label: 'NCCN, 2025, - NCCN Colon Cancer Guidelines v1.2025' },
        { label: 'ASCO, 2024, - ASCO PCO 2024 — CRC ctDNA' },
      ],
      guidelines: 'ctDNA MRD testing is endorsed by both NCCN (Category 2A for stage II) and ASCO (PCO for stages II-III) for colorectal cancer.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive ctDNA result gives your doctor important information about your risk of cancer returning and helps guide treatment decisions. In stage II colorectal cancer, the DYNAMIC trial showed that ctDNA testing can help doctors decide whether you need chemotherapy - reducing unnecessary treatment by nearly half while maintaining the same cure rates. For ctDNA-positive patients, studies like GALAXY show that adjuvant chemotherapy significantly reduces the risk of recurrence compared to observation alone.',
      forDoctor: 'ctDNA positivity provides actionable prognostic and predictive information across CRC stages. In stage II disease, the DYNAMIC trial (N=455) demonstrated ctDNA-guided management reduced adjuvant chemotherapy from 28% to 15% while maintaining non-inferior 5-year RFS (88% vs 87%, HR 1.05, P=0.887; PMID: 35657320, 40055522). For ctDNA-positive patients, GALAXY/VEGA (N>2,000) showed adjuvant chemotherapy significantly improved DFS vs observation (HR 0.39; PMID: 36646802). ctDNA positivity confers substantial recurrence risk (HR 11.99 for DFS, HR 9.68 for OS) and provides 3-12 months lead time before radiographic recurrence (PMID: 31070691). In refractory disease, ALTAIR demonstrated FTD/TPI benefit in Signatera-positive patients (median DFS 9.23 vs 5.55 months, HR 0.75, 95% CI 0.55-0.98, P=0.0406). For dMMR stage III disease, adjuvant atezolizumab plus chemotherapy is supported.',
      stageNotes: {
        'stage-1': 'Limited evidence from ALTAIR trial supports FTD/TPI for ctDNA-positive recurrent disease.',
        'stage-2': 'DYNAMIC trial supports ctDNA-guided de-escalation of adjuvant chemotherapy, while GALAXY shows benefit of treatment in ctDNA-positive patients.',
        'stage-3': 'GALAXY data support adjuvant chemotherapy in ctDNA-positive patients, with atezolizumab plus chemotherapy for dMMR tumors.',
        'stage-4': 'ALTAIR trial demonstrates FTD/TPI benefit in Signatera-positive patients with refractory disease.',
      },
      sources: [
        { label: 'Tie et al., New England Journal of Medicine, 2022, - Circulating tumor DNA analysis guiding adjuvant therapy in stage II colon cancer', pmid: '35657320' },
        { label: 'Tie et al., Nature Medicine, 2025, - DYNAMIC 5-year follow-up', pmid: '40055522' },
        { label: 'Kotani et al., Nature Medicine, 2023, - GALAXY/VEGA study', pmid: '36646802' },
        { label: 'ALTAIR investigators, 2026, - ALTAIR trial' },
        { label: 'CITCCA investigators, 2026, - CITCCA study' },
        { label: 'Guardant investigators, Journal of Clinical Oncology, 2026, - Guardant Reveal stage III CRC study' },
        { label: 'Reinert et al., JAMA Oncology, 2019, - Analysis of ctDNA to Predict Outcome after Surgery and Adjuvant Treatment in Colorectal Cancer', pmid: '31070691' },
        { label: 'Jiang et al., J Gastrointest Surg, 2026, - The role of ctDNA in precision adjuvant therapy for colorectal cancer: a scoping review.', pmid: '41935608' },
        { label: 'Ismaili N, Cancer Invest, 2026, - Practice-Changing Trials in Gastrointestinal Cancers at ASCO 2025: A Critical Review and Clinical Context.', pmid: '41960736' },
      ],
      guidelines: 'DYNAMIC and GALAXY trials provide Level 1 evidence supporting ctDNA-guided adjuvant therapy decisions in stages II-III CRC.',
    },

    'not-validated': {
      forPatient: 'ctDNA testing has been extensively studied in colorectal cancer with strong validation data. The COSMOS trial showed 98.2% accuracy in correctly identifying patients without cancer, and the test can detect recurrence an average of 5.3 months before scans would catch it. While your doctor is right to consider validation carefully, colorectal cancer actually has some of the strongest evidence supporting ctDNA testing among all cancer types.',
      forDoctor: 'ctDNA testing in colorectal cancer has substantial validation through multiple trials. COSMOS demonstrated 98.2% analytical specificity with 5.3-month median lead time over imaging. The Alliance N0147 phase III trial (PMID: 41931716, Sinicrope et al., J Clin Oncol 2026) provides additional outcome data for tissue-free ctDNA assays with FOLFOX-based adjuvant therapy. Key validation considerations include distinguishing clinical from analytical sensitivity/specificity, understanding that landmark sensitivity differs from longitudinal sensitivity across multiple timepoints, and recognizing that LOD comparisons across platforms require careful interpretation due to methodological differences. Stage II disease presents greater MRD detection challenges due to lower tumor burden but often represents the highest clinical impact scenario for treatment decisions.',
      stageNotes: {
        'stage-2': 'Stage II colorectal cancers present the greatest challenge for ctDNA detection due to lower tumor burden and less circulating DNA, yet this is often where MRD-guided treatment decisions have the most clinical impact.',
      },
      sources: [
        { label: 'COSMOS investigators, - COSMOS study' },
        { label: 'Sinicrope et al., J Clin Oncol, 2026, - Erratum: Tissue-Free Circulating Tumor DNA Assay and Patient Outcome in a Phase III Trial of FOLFOX-Based Adjuvant Chemotherapy (Alliance N0147).', pmid: '41931716' },
      ],
      guidelines: 'Colorectal cancer has extensive validation data for ctDNA testing, though coverage policies vary by indication and clinical scenario.',
    },

  },

  /* ═══════════════════════════════════════════
   *  BREAST — Tier 1
   * ═══════════════════════════════════════════ */
  breast: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t directly improve outcomes, it provides valuable information that can guide your treatment decisions. Studies like c-TRAK TN and DARE show that ctDNA testing can detect cancer recurrence 3-12 months before it shows up on scans, giving you and your doctor more time to adjust treatment. In the DARE trial, patients who switched treatments based on ctDNA results had better clearance rates, and those who remained ctDNA-negative stayed cancer-free in 99.5% of cases.',
      forDoctor: 'While direct outcome benefits remain under investigation, emerging evidence supports MRD testing\'s clinical utility in breast cancer. The c-TRAK TN trial (PMID: 36423745) demonstrated ctDNA surveillance detects recurrence 6-12 months earlier than imaging in TNBC. The DARE trial showed actionable results: of 507 high-risk HR+/HER2- patients, 60 were ctDNA-positive, and switching to palbociclib + fulvestrant achieved 2-fold higher ctDNA clearance at 3 months. Critically, 99.5% of patients with sustained ctDNA negativity remained recurrence-free at 27.4 months. ABCSG-34 (PMID: 41951687) provides long-term validation with 7.1-year median follow-up (n=109), showing baseline ctDNA positivity significantly associated with inferior OS (HR 2.12, p=0.043). The consistent 3-12 month lead time (PMID: 31070691) offers a therapeutic window for intervention.',
      sources: [
        { label: '- c-TRAK TN — ctDNA surveillance in TNBC', pmid: '36423745' },
        { label: '2025, - DARE trial — ASCO 2025 interim' },
        { label: 'Egle et al., NPJ Breast Cancer, 2026, - Long-term prognostic value of ctDNA in early breast cancer: insights from the neoadjuvant ABCSG-34 Trial.', pmid: '41951687' },
      ],
      guidelines: 'Current guidelines do not universally recommend routine MRD testing in breast cancer, though emerging evidence supports its integration into clinical decision-making.',
    },

    'not-in-guidelines': {
      forPatient: 'While MRD testing isn\'t yet in official cancer treatment guidelines, Medicare does cover this test for breast cancer patients, which shows it\'s recognized as valuable. The fact that Medicare covers it means there\'s enough evidence supporting its clinical usefulness. You can discuss with your doctor whether this test might help guide your specific treatment decisions.',
      forDoctor: 'While major oncology guidelines have not yet incorporated routine MRD testing recommendations, Medicare provides coverage for tumor-informed ctDNA MRD testing across solid tumors including breast cancer through MolDX LCD L39256. This coverage reflects CMS recognition of sufficient clinical evidence supporting the utility of MRD testing. The test can provide prognostic information and may inform adjuvant therapy decisions, particularly in early-stage disease where residual disease detection could guide treatment intensification or duration.',
      sources: [
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'MRD testing is not currently included in major breast cancer treatment guidelines, though Medicare provides coverage through MolDX policy.',
    },

    'what-to-do-positive': {
      forPatient: 'When ctDNA testing shows cancer DNA in your blood, your doctor has several proven options to help. Studies like the DARE trial show that switching treatments based on ctDNA results can double the chances of clearing cancer DNA from your blood. The c-TRAK TN study found that ctDNA testing detects cancer returning 6-12 months earlier than scans, giving you and your doctor more time to act before cancer spreads.',
      forDoctor: 'Positive ctDNA results provide actionable clinical information with established interventions. The DARE trial demonstrated that treatment switching based on ctDNA positivity achieved twofold higher ctDNA clearance at 3 months in HR+/HER2- patients (n=60/507). c-TRAK TN showed ctDNA surveillance detects recurrence 6-12 months earlier than imaging in TNBC (PMID: 36423745), providing substantial lead time for intervention. ABCSG-34 confirmed prognostic value with baseline ctDNA positivity associated with inferior OS (HR 2.12, p=0.043, n=109, median follow-up 7.1 years; PMID: 41951687). Patients maintaining ctDNA negativity showed 99.5% recurrence-free survival at 27.4 months in DARE, supporting treatment intensification strategies for ctDNA-positive patients.',
      sources: [
        { label: '- c-TRAK TN — ctDNA surveillance in TNBC', pmid: '36423745' },
        { label: '2025, - DARE trial — ASCO 2025 interim' },
        { label: 'Egle et al., NPJ Breast Cancer, 2026, - Long-term prognostic value of ctDNA in early breast cancer: insights from the neoadjuvant ABCSG-34 Trial.', pmid: '41951687' },
      ],
      guidelines: 'DARE and c-TRAK TN trials support treatment modification and intensified surveillance for ctDNA-positive patients, with 6-12 month lead time enabling early intervention before radiographic recurrence.',
    },

    'not-validated': {
      forPatient: 'While MRD testing may not be specifically validated for all breast cancer subtypes, there is strong evidence supporting its use, particularly in triple-negative breast cancer where positive results after chemotherapy predict recurrence with over 95% accuracy. The COSMOS trial showed that MRD testing can detect cancer recurrence an average of 5.3 months before standard imaging, with very high accuracy (98.2% specificity). Your oncologist may be concerned about validation, but the technology has shown meaningful clinical benefit in breast cancer patients.',
      forDoctor: 'ctDNA MRD testing has demonstrated robust clinical validation in breast cancer, particularly TNBC where post-neoadjuvant ctDNA positivity shows >95% PPV for recurrence (PMID: 36423745). The Guardant Reveal platform achieved 98.2% specificity in the COSMOS trial with 5.3-month median lead time over standard surveillance. Key considerations include distinguishing clinical vs analytical sensitivity/specificity, landmark vs longitudinal sensitivity metrics, and recognizing that Stage II cancers pose detection challenges despite representing optimal MRD-guided therapy candidates. Serial testing requires high analytical specificity (>99%) to minimize cumulative false positives over multiple timepoints. Clinical sensitivity from interventional trials requires careful interpretation due to treatment effects on MRD+ patients.',
      stageNotes: {
        'stage-2': 'Stage II cancers present the greatest MRD detection challenge due to lower tumor burden and less circulating tumor DNA, yet represent where MRD-guided therapy decisions often have the most clinical impact.',
      },
      sources: [
        { label: '- c-TRAK TN — ctDNA surveillance in TNBC', pmid: '36423745' },
      ],
      guidelines: 'MRD testing validation varies by platform and cancer subtype, with strongest evidence in triple-negative breast cancer; insurance coverage remains limited and varies by indication.',
    },

  },

  /* ═══════════════════════════════════════════
   *  LUNG (NSCLC) — Tier 1
   * ═══════════════════════════════════════════ */
  lung: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t directly cure cancer, it provides crucial information that helps your oncologist make better treatment decisions and catch recurrence much earlier. Studies like IMpower010 show that patients with detectable ctDNA after surgery benefit significantly more from immunotherapy, while those without detectable ctDNA may avoid unnecessary treatment. Research also shows ctDNA can detect cancer recurrence 3-12 months before it shows up on scans, giving you and your doctor valuable time to adjust treatment plans.',
      forDoctor: 'Multiple trials demonstrate MRD testing guides treatment decisions and improves outcomes in NSCLC. IMpower010 showed ctDNA-positive patients had significantly improved DFS with adjuvant atezolizumab vs BSC. AEGEAN demonstrated patients without ctDNA clearance during neoadjuvant treatment or with post-surgical MRD had worse outcomes with perioperative durvalumab. TRACERx (PMID: 37055640) achieved median 164-day lead time before clinical relapse using PhasED-Seq in 197 patients with 1,069 samples. DART showed detectable ctDNA during consolidative durvalumab predicts progression 7.4 months before radiological evidence. A 2025 meta-analysis of 13 studies (n=1,309) confirmed longitudinal ctDNA monitoring as strongest prognostic signal (HR 8.70). Lead time from ctDNA detection to radiographic recurrence ranges 3-12 months (Reinert et al., JAMA Oncology 2019, PMID: 31070691).',
      stageNotes: {
        'stage-1': 'ctDNA clearance post-surgery predicts benefit from adjuvant atezolizumab in stage IB-IIIA disease (IMpower010).',
        'stage-2': 'ctDNA clearance post-surgery predicts benefit from adjuvant atezolizumab in stage IB-IIIA disease (IMpower010).',
        'stage-3': 'ctDNA clearance post-surgery predicts benefit from adjuvant atezolizumab in stage IB-IIIA disease (IMpower010).',
      },
      sources: [
        { label: '- IMpower010 — ctDNA and adjuvant atezolizumab' },
        { label: '- TRACERx — ultrasensitive ctDNA in NSCLC', pmid: '37055640' },
        { label: '2025, - AEGEAN exploratory analysis — ASCO 2025' },
        { label: '2025, - DART trial — ASCO 2025' },
        { label: 'JCO Precision Oncology, 2025, - NSCLC ctDNA meta-analysis — JCO Precision Oncology 2025' },
      ],
      guidelines: 'Current evidence supports MRD testing for treatment selection in resectable NSCLC, particularly for adjuvant immunotherapy decisions.',
    },

    'not-in-guidelines': {
      forPatient: 'You\'re right that MRD testing isn\'t in official treatment guidelines yet - the NCCN recognizes it as a promising emerging tool but hasn\'t made specific recommendations. However, this doesn\'t mean it\'s not valuable or available to you. Medicare actually covers this testing for lung cancer patients, which shows there\'s real clinical value even while guidelines catch up to the science.',
      forDoctor: 'While NCCN NSCLC Guidelines acknowledge ctDNA as an emerging tool, they have not yet incorporated specific MRD testing recommendations into standard care pathways. However, Medicare coverage through MolDX LCD L39256 for tumor-informed ctDNA MRD testing across solid tumors, including NSCLC, suggests payer recognition of clinical utility. The lag between evidence generation and guideline incorporation is common, particularly for newer technologies where real-world data continues to accumulate.',
      sources: [
        { label: '2025, - NCCN NSCLC Guidelines v3.2025' },
      ],
      guidelines: 'NCCN recognizes ctDNA as emerging but lacks specific MRD recommendations; Medicare provides coverage through MolDX.',
    },

    'what-to-do-positive': {
      forPatient: 'When ctDNA testing shows positive results after surgery, your doctor has several important options to help you. The test can guide whether you might benefit from immunotherapy treatments like atezolizumab, and it provides an early warning system that can detect cancer returning months before scans would show it. This early detection gives your medical team valuable time to adjust your treatment plan and potentially catch any recurrence when it\'s most treatable.',
      forDoctor: 'Positive ctDNA results provide actionable clinical information across multiple contexts. In IMpower010, ctDNA-positive patients with stage IB-IIIA NSCLC demonstrated significantly improved DFS with adjuvant atezolizumab versus BSC. For surveillance, ctDNA detection provides substantial lead time (median 164 days in TRACERx, 3-12 months per Reinert et al. JAMA Oncol 2019, PMID: 31070691), enabling earlier intervention. The AEGEAN trial showed patients without ctDNA clearance during neoadjuvant treatment had worse outcomes with perioperative durvalumab, while DART demonstrated ctDNA positivity during consolidative durvalumab predicts progression 7.4 months before radiological evidence. A recent meta-analysis of 1,309 patients confirmed longitudinal ctDNA monitoring as the strongest prognostic signal (HR 8.70, JCO Precision Oncology 2025).',
      stageNotes: {
        'stage-1': 'ctDNA clearance post-surgery predicts benefit from adjuvant atezolizumab in stage IB-IIIA NSCLC per IMpower010.',
        'stage-2': 'ctDNA clearance post-surgery predicts benefit from adjuvant atezolizumab in stage IB-IIIA NSCLC per IMpower010.',
        'stage-3': 'ctDNA clearance post-surgery predicts benefit from adjuvant atezolizumab in stage IB-IIIA NSCLC per IMpower010.',
      },
      sources: [
        { label: '- IMpower010 — ctDNA and adjuvant atezolizumab' },
        { label: '- TRACERx — ultrasensitive ctDNA in NSCLC', pmid: '37055640' },
        { label: '2025, - AEGEAN exploratory analysis — ASCO 2025' },
        { label: '2025, - DART trial — ASCO 2025' },
        { label: 'JCO Precision Oncology, 2025, - NSCLC ctDNA meta-analysis — JCO Precision Oncology 2025' },
      ],
      guidelines: 'Consider adjuvant immunotherapy for ctDNA-positive patients based on IMpower010 data and utilize ctDNA monitoring for early recurrence detection.',
    },

    'not-validated': {
      forPatient: 'While MRD testing for lung cancer is still being studied, there is promising research showing these tests can work well in lung cancer patients. The TRACERx study demonstrated that newer, more sensitive testing methods can detect very small amounts of cancer DNA in the blood of lung cancer patients. Your doctor may be cautious because the test hasn\'t been studied as extensively in lung cancer as in some other cancer types, but the available evidence suggests it can be clinically useful.',
      forDoctor: 'MRD testing validation in lung cancer has advanced significantly with data from the TRACERx study (PMID: 37055640). PhasED-Seq demonstrated superior performance with LOD95 of 1 ppm versus 84 ppm for CAPP-Seq, achieving clinical sensitivity of 67% versus 28% (P=0.022). Guardant Reveal showed 98.2% specificity with 5.3-month median lead time in the COSMOS trial. When evaluating MRD test performance, distinguish between clinical sensitivity (percentage of recurred patients correctly identified) versus analytical sensitivity, and landmark versus longitudinal sensitivity metrics. Stage II lung cancers present particular MRD detection challenges due to lower tumor burden but may benefit most from MRD-guided therapy decisions. Consider that clinical sensitivity from interventional trials requires careful interpretation due to treatment effects on MRD-positive patients.',
      sources: [
        { label: '- TRACERx — ultrasensitive ctDNA in NSCLC', pmid: '37055640' },
      ],
      guidelines: 'MRD testing in lung cancer lacks formal guideline endorsement but has emerging clinical validation data from prospective studies.',
    },

  },

  /* ═══════════════════════════════════════════
   *  BLADDER — Tier 2
   * ═══════════════════════════════════════════ */
  bladder: {
    'no-evidence': {
      forPatient: 'Actually, there\'s now strong evidence that MRD testing can guide treatment decisions that improve outcomes in bladder cancer. The landmark IMvigor011 trial published in the New England Journal of Medicine showed that patients with detectable ctDNA who received immunotherapy lived significantly longer than those who didn\'t - with survival extending from about 21 months to nearly 33 months. This represents the first time any cancer type has proven that acting on positive MRD results actually saves lives.',
      forDoctor: 'Recent Level 1 evidence directly contradicts this concern. IMvigor011 (NEJM 2024, PMID: 41124204) demonstrated significant survival benefit from ctDNA-guided adjuvant atezolizumab in muscle-invasive bladder cancer. Among 250 ctDNA+ patients randomized 2:1, atezolizumab improved median DFS (9.9 vs 4.8 months, HR 0.64, P=0.0047) and OS (32.8 vs 21.1 months). Twelve-month outcomes showed DFS 44.7% vs 30.0% and OS 85.1% vs 70.0% for atezolizumab vs placebo. Notably, ctDNA-negative patients (n=511) had excellent outcomes with 12-month DFS 95.4% and OS 100%, supporting a watch-and-wait approach. This represents the first randomized trial proving that intervening on positive ctDNA improves survival in any cancer type.',
      stageNotes: {
        'stage-2': 'IMvigor011 data applies to muscle-invasive bladder cancer including Stage II disease with proven survival benefit from ctDNA-guided adjuvant immunotherapy.',
        'stage-3': 'IMvigor011 data applies to muscle-invasive bladder cancer including Stage III disease with proven survival benefit from ctDNA-guided adjuvant immunotherapy.',
      },
      sources: [
        { label: 'Powles et al., NEJM, 2024, - IMvigor011', pmid: '41124204' },
      ],
      guidelines: 'IMvigor011 provides the first Level 1 evidence for ctDNA-guided intervention in any cancer type, likely to influence future guideline recommendations.',
    },

    'not-in-guidelines': {
      forPatient: 'While ctDNA testing isn\'t yet in official cancer treatment guidelines for bladder cancer, Medicare does cover this testing for solid tumors, including bladder cancer, which shows growing recognition of its clinical value. Your doctor may be hesitant because guidelines often take time to catch up with emerging technologies, but the test is available and covered by insurance if your medical team determines it could be helpful for monitoring your treatment response.',
      forDoctor: 'Although ctDNA MRD testing is not yet incorporated into major oncology guidelines for bladder cancer, Medicare coverage is established through MolDX LCD L39256 for tumor-informed ctDNA across solid tumors, including urothelial carcinoma. This coverage decision reflects CMS recognition of clinical utility despite the lag in formal guideline adoption. Consider that guidelines typically require extensive validation data and consensus processes that may not keep pace with emerging technologies that already demonstrate clinical value in practice.',
      sources: [
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'ctDNA MRD testing is not currently included in major bladder cancer treatment guidelines, though Medicare coverage is established for solid tumors.',
    },

    'what-to-do-positive': {
      forPatient: 'If your ctDNA test comes back positive after bladder cancer treatment, your doctor now has a proven treatment option. The IMvigor011 study showed that patients with positive ctDNA tests who received atezolizumab immunotherapy lived longer without their cancer returning compared to those who didn\'t receive treatment. This gives your oncologist a clear, evidence-based plan to help improve your outcomes if the test is positive.',
      forDoctor: 'IMvigor011 provides Level 1 evidence for ctDNA-guided intervention in bladder cancer. In this Phase III trial (N=250 ctDNA+ patients), adjuvant atezolizumab significantly improved DFS (HR 0.64, 95% CI not provided, P=0.0047) with median DFS 9.9 vs 4.8 months compared to placebo. OS benefit was also demonstrated (median 32.8 vs 21.1 months). At 12 months, DFS was 44.7% vs 30.0% and OS was 85.1% vs 70.0% for atezolizumab vs placebo, respectively. ctDNA-negative patients had excellent outcomes (12-month DFS 95.4%, OS 100%), confirming the prognostic value. This represents the first randomized evidence supporting therapeutic intervention based on positive ctDNA in any adjuvant cancer setting (PMID: 41124204).',
      stageNotes: {
        'stage-2': 'IMvigor011 demonstrated significant DFS and OS benefit with adjuvant atezolizumab for ctDNA-positive patients (HR 0.64, P=0.0047).',
        'stage-3': 'IMvigor011 demonstrated significant DFS and OS benefit with adjuvant atezolizumab for ctDNA-positive patients (HR 0.64, P=0.0047).',
      },
      sources: [
        { label: 'Powles et al., NEJM, 2024, - IMvigor011', pmid: '41124204' },
      ],
      guidelines: 'IMvigor011 provides the first Level 1 evidence supporting adjuvant atezolizumab for ctDNA-positive bladder cancer patients.',
    },

    'not-validated': {
      forPatient: 'While MRD testing hasn\'t been specifically validated in large bladder cancer studies yet, the COSMOS trial showed that ctDNA tests can detect cancer recurrence with 98% accuracy and identify it about 5 months before standard scans would catch it. Your doctor might be concerned because most MRD validation has focused on other cancer types, but the underlying technology works similarly across different cancers. It\'s worth discussing whether the potential benefits of early detection might outweigh the current limitations in bladder-specific data.',
      forDoctor: 'While bladder cancer lacks dedicated MRD validation studies, the COSMOS trial demonstrated Guardant Reveal\'s 98.2% specificity with 5.3-month median lead time over radiographic detection. Key considerations include distinguishing clinical vs analytical sensitivity/specificity, as clinical sensitivity from interventional trials requires careful interpretation due to treatment effects obscuring true recurrence rates. Landmark sensitivity (single timepoint) typically yields lower detection rates than longitudinal monitoring. LOD comparisons across platforms aren\'t directly comparable due to methodological differences, and cfDNA input amounts may be as relevant as blood volume for assay performance.',
      stageNotes: {
        'stage-ii': 'Stage II bladder cancers present the greatest MRD detection challenge due to lower tumor burden and less circulating tumor DNA, yet represent where MRD-guided therapy decisions often have the most clinical impact.',
      },
      sources: [
        { label: 'Guardant Health, - COSMOS specificity' },
        { label: 'Guardant Health, - COSMOS lead time' },
        { label: 'MR, 2024, - OpenOnco Expert Advisory Panel' },
      ],
      guidelines: 'MRD testing in bladder cancer currently lacks specific clinical validation studies and guideline recommendations for routine use.',
    },

  },

  /* ═══════════════════════════════════════════
   *  MELANOMA — Tier 2
   * ═══════════════════════════════════════════ */
  melanoma: {
    'no-evidence': {
      forPatient: 'While MRD testing in melanoma doesn\'t directly change survival outcomes yet, it provides valuable information about your cancer\'s behavior and treatment response. The COMBI-AD study showed that patients with detectable ctDNA had nearly 3 times higher risk of cancer returning, regardless of treatment. This early detection can give you and your doctor a 3-12 month head start to monitor more closely or potentially adjust treatment plans.',
      forDoctor: 'Recent evidence demonstrates MRD testing\'s prognostic value in melanoma, though therapeutic interventions based on results remain investigational. The COMBI-AD biomarker analysis (N=597 stage III patients, 60-month follow-up) showed ctDNA+ patients had significantly increased recurrence risk in both placebo (HR 2.91, p=0.0001) and targeted therapy arms (HR 2.98, p=0.0001) compared to ctDNA- patients (PMID: 40250457). In metastatic disease, 6-month ctDNA clearance during adjuvant immunotherapy (47.4% of patients) was associated with dramatically improved PFS (HR 10.0, p=0.03) (PMID: 39169411). ctDNA detection provides 3-12 month lead time before radiographic recurrence, enabling intensified surveillance and potential early intervention strategies.',
      stageNotes: {
        'stage-3': 'COMBI-AD data shows ctDNA positivity increases recurrence risk 3-fold regardless of adjuvant targeted therapy.',
        'stage-4': 'ctDNA clearance at 6 months during immunotherapy strongly predicts improved progression-free survival.',
      },
      sources: [
        { label: 'COMBI-AD investigators et al., Lancet Oncology, 2026, - COMBI-AD biomarker analysis', pmid: '40250457' },
        { label: 'Lee et al., - ctDNA in resected melanoma', pmid: '39169411' },
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'Medicare provides coverage for tumor-informed ctDNA testing in melanoma through MolDX guidelines.',
    },

    'not-in-guidelines': {
      forPatient: 'While NCCN guidelines don\'t yet include specific recommendations for ctDNA testing in melanoma, this doesn\'t mean the test isn\'t valuable or available. Medicare does cover this type of testing for solid tumors including melanoma, which suggests growing recognition of its clinical utility. Your doctor may still consider ctDNA testing based on emerging research and your individual situation, even without formal guideline recommendations.',
      forDoctor: 'Current NCCN Melanoma guidelines lack specific ctDNA MRD recommendations, reflecting the evolving nature of this biomarker in melanoma management. However, Medicare coverage through MolDX LCD L39256 for tumor-informed ctDNA MRD testing across solid tumors, including melanoma, indicates payer recognition of clinical utility. Consider discussing with patient that absence from guidelines doesn\'t preclude clinical application, particularly given Medicare coverage and emerging evidence in melanoma MRD detection.',
      sources: [
        { label: 'NCCN, 2025, - NCCN Melanoma Guidelines v2.2025' },
      ],
      guidelines: 'NCCN Melanoma guidelines do not currently include ctDNA MRD testing recommendations, though Medicare provides coverage for solid tumors including melanoma.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive ctDNA test gives your doctor important information about your melanoma risk and treatment response. The COMBI-AD study showed that patients with detectable ctDNA had nearly 3 times higher risk of cancer returning, which helps guide decisions about more intensive monitoring or additional treatment. ctDNA can detect cancer returning 3-12 months before it shows up on scans, giving you and your doctor time to adjust your treatment plan early.',
      forDoctor: 'Positive ctDNA results provide actionable prognostic information and guide clinical decision-making in melanoma. The COMBI-AD biomarker analysis (N=597, 60-month follow-up) demonstrated that ctDNA+ patients had significantly increased recurrence risk in both placebo (HR 2.91, p=0.0001) and targeted therapy arms (HR 2.98, p=0.0001) (PMID: 40250457). ctDNA dynamics correlate with clinical outcomes during adjuvant immunotherapy, with 6-month clearance (47.4%) associated with improved PFS (HR 10.0, p=0.03) (PMID: 39169411). Positive results enable intensified surveillance protocols, potential treatment modification, and early intervention given the 3-12 month lead time before radiographic recurrence (PMID: 31070691). Medicare covers tumor-informed ctDNA assays via MolDX.',
      stageNotes: {
        'stage-3': 'COMBI-AD data shows ctDNA+ stage III patients have ~3-fold increased recurrence risk regardless of adjuvant targeted therapy.',
        'stage-4': 'ctDNA clearance at 6 months during treatment is associated with significantly improved progression-free survival (HR 10.0).',
      },
      sources: [
        { label: 'COMBI-AD investigators et al., Lancet Oncology, 2026, - COMBI-AD biomarker analysis', pmid: '40250457' },
        { label: 'Lee et al., - ctDNA in resected melanoma', pmid: '39169411' },
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'COMBI-AD provides Level 1 evidence for ctDNA prognostic utility in stage III melanoma; consider intensified surveillance and potential treatment modifications based on ctDNA status.',
    },

    'not-validated': {
      forPatient: 'While ctDNA testing isn\'t formally validated specifically for melanoma like it is for some other cancers, there is emerging research showing it can detect cancer DNA in melanoma patients. Studies have found that ctDNA can be detected in about 13% of stage III melanoma patients after surgery and in over 90% of patients with advanced melanoma. Your doctor may be cautious because the test performance can vary significantly depending on your specific stage and situation.',
      forDoctor: 'ctDNA testing in melanoma shows stage-dependent detection rates with limited but growing validation data. In the COMBI-AD trial (N=597), baseline ctDNA detection was only 13% in stage III patients (PMID: 40250457), while Lee et al. reported 91.7% pre-ICI ctDNA positivity in stage IV disease (PMID: 39169411). The Guardant Reveal COSMOS trial demonstrated 98.2% specificity with 5.3-month median lead time, though clinical sensitivity varies significantly by stage and tumor burden. Stage II-III melanomas present particular MRD detection challenges due to lower circulating tumor DNA levels, and landmark sensitivity typically yields lower detection rates than longitudinal monitoring across multiple timepoints.',
      stageNotes: {
        'stage-3': 'Stage III melanoma shows relatively low ctDNA detection rates at baseline (13% in COMBI-AD), making MRD testing more challenging than in higher-stage disease.',
        'stage-4': 'Stage IV melanoma demonstrates high ctDNA positivity rates (91.7% pre-immunotherapy), making molecular monitoring more feasible in advanced disease.',
      },
      sources: [
        { label: 'COMBI-AD investigators et al., Lancet Oncology, 2026, - COMBI-AD biomarker analysis', pmid: '40250457' },
        { label: 'Lee et al., - ctDNA in resected melanoma', pmid: '39169411' },
      ],
      guidelines: 'ctDNA testing in melanoma lacks formal validation compared to established uses in colorectal and breast cancers, with limited coverage policies.',
    },

  },

  /* ═══════════════════════════════════════════
   *  DEFAULT — Tier 3 (generic fallback)
   * ═══════════════════════════════════════════ */
  _default: {
    'no-evidence': {
      forPatient: 'While MRD testing doesn\'t directly change survival outcomes, it can detect cancer recurrence 3-12 months before it shows up on scans, giving you and your doctor more time to make treatment decisions. Studies like the one by Reinert show this early warning system can be valuable for monitoring your response to treatment and planning next steps. The test results help predict how well treatments are working, which can guide important decisions about your care.',
      forDoctor: 'While direct outcome benefit remains under investigation, ctDNA/MRD testing provides clinically relevant prognostic information with lead time advantages. Reinert et al. (PMID: 31070691) demonstrated 3-12 month lead time from ctDNA detection to radiographic recurrence across solid tumors. In IDH-mutant cholangiocarcinoma, Yumashev et al. (PMID: 41912863) showed ctDNA dynamics including persistent postoperative/post-chemotherapy positivity and rising levels during IDH inhibitor treatment correlate with worse DFS and OS. This molecular surveillance enables earlier clinical decision-making regarding treatment modifications, additional imaging, or clinical trial enrollment, potentially improving patient management even without proven survival benefit.',
      sources: [
        { label: 'Reinert et al., JAMA Oncology, 2019, - lead time', pmid: '31070691' },
        { label: 'Yumashev et al., Clin Transl Oncol, 2026, - Circulating tumor DNA-based detection of molecular residual disease in isocitrate dehydrogenase-mutant cholangiocarcinoma for biomarker-guided therapy.', pmid: '41912863' },
      ],
      guidelines: 'Current guidelines generally position MRD testing as investigational for most solid tumors, with emerging evidence supporting clinical utility for treatment monitoring and recurrence surveillance.',
    },

    'not-in-guidelines': {
      forPatient: 'While MRD testing isn\'t yet included in formal cancer treatment guidelines, Medicare does cover tumor-informed ctDNA testing for solid tumors, which shows the medical community recognizes its clinical value. Many oncologists are using this testing to help guide treatment decisions even before official guideline inclusion. You can discuss with your doctor whether MRD testing might be helpful in your specific situation.',
      forDoctor: 'While awaiting formal guideline inclusion, tumor-informed ctDNA MRD testing has Medicare coverage across solid tumors per MolDX LCD L39256, indicating CMS recognition of clinical utility. Many oncologists are incorporating MRD testing into clinical practice for treatment monitoring and recurrence detection. The lack of guideline inclusion doesn\'t preclude clinical use when appropriate for individual patient management.',
      sources: [
        { label: 'CMS, - CMS MolDX LCD L39256' },
      ],
      guidelines: 'MRD testing is not yet included in major oncology guidelines but has Medicare coverage recognition.',
    },

    'what-to-do-positive': {
      forPatient: 'A positive ctDNA test can give your doctor important information about your cancer 3-12 months before it might show up on scans. This early warning could allow your medical team to adjust your treatment plan sooner, potentially improving your outcomes. While the best approach varies by cancer type, having this advance notice gives you and your doctor more time to make informed decisions about your care.',
      forDoctor: 'Positive ctDNA results provide 3-12 months lead time before radiographic recurrence (Reinert et al., JAMA Oncol 2019, PMID: 31070691), enabling earlier therapeutic intervention. ctDNA dynamics, including persistent postoperative positivity or rising levels during treatment, correlate with worse DFS and OS (Yumashev et al., Clin Transl Oncol 2026, PMID: 41912863). Clinical actions may include intensified surveillance, earlier imaging, consideration of adjuvant therapy escalation, or enrollment in MRD-directed clinical trials. The specific intervention depends on tumor type, stage, and available therapeutic options.',
      sources: [
        { label: 'Reinert et al., JAMA Oncology, 2019, - lead time', pmid: '31070691' },
        { label: 'Yumashev et al., Clin Transl Oncol, 2026, - Circulating tumor DNA-based detection of molecular residual disease in isocitrate dehydrogenase-mutant cholangiocarcinoma for biomarker-guided therapy.', pmid: '41912863' },
      ],
      guidelines: 'Consider enrollment in MRD-directed clinical trials or intensified surveillance protocols for positive results.',
    },

    'not-validated': {
      forPatient: 'While MRD testing may not have been specifically studied in your exact cancer type, the technology itself has shown promise across many solid tumors. In the COSMOS study, the Guardant Reveal test demonstrated 98.2% accuracy in correctly identifying patients without disease and could detect cancer returning an average of 5.3 months before imaging scans. Your doctor may be concerned about how well the test performs in your specific situation, which is an important consideration for making treatment decisions.',
      forDoctor: 'MRD validation varies significantly across cancer types and clinical contexts. The Guardant Reveal COSMOS study demonstrated 98.2% analytical specificity with 5.3-month median lead time over imaging, though clinical sensitivity differs from analytical sensitivity and should be distinguished when interpreting performance. Key considerations include: landmark vs longitudinal sensitivity metrics, analytical vs clinical specificity (99% analytical specificity yields ~5% cumulative false positive probability over 5 serial tests), and three distinct use cases (landmark post-surgery, treatment response, surveillance) with different performance requirements. LOD comparisons across platforms are not directly comparable due to methodological differences, and clinical sensitivity from interventional trials requires careful interpretation due to treatment effects on MRD-positive patients.',
      stageNotes: {
        'stage-2': 'Stage II cancers present the greatest MRD detection challenge due to lower tumor burden and less circulating tumor DNA, yet represent where MRD-guided therapy decisions often have the most impact.',
      },
      sources: [
        { label: 'Guardant Health, - COSMOS specificity' },
        { label: 'Guardant Health, - COSMOS lead time' },
        { label: 'MR, 2024, - OpenOnco Expert Advisory Panel' },
      ],
      guidelines: 'MRD testing validation status varies by cancer type, with most evidence from colorectal, breast, and lung cancers.',
    },

  },
};
