#!/usr/bin/env node

/**
 * Send escalation email via Resend API.
 * Called by the GitHub Action when there are escalated items.
 *
 * Usage:
 *   node scripts/auto-triage/notify.js [pr-url]
 *
 * Environment:
 *   RESEND_API_KEY — required
 *   ALERT_EMAIL    — recipient (default: alexgdickinson@gmail.com)
 */

import { readFileSync, existsSync } from 'fs';
import { Resend } from 'resend';

const ESCALATION_FILE = '/tmp/triage-escalations.json';
const FROM_EMAIL = 'OpenOnco Daemon <daemon@openonco.org>';
const TO_EMAIL = process.env.ALERT_EMAIL || 'alexgdickinson@gmail.com';

async function main() {
  if (!existsSync(ESCALATION_FILE)) {
    console.log('No escalation file found, nothing to send.');
    return;
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.error('RESEND_API_KEY not set, skipping email');
    return;
  }

  const data = JSON.parse(readFileSync(ESCALATION_FILE, 'utf-8'));
  if (!data.items || data.items.length === 0) {
    console.log('No escalated items, nothing to send.');
    return;
  }

  const prUrl = process.argv[2] || '(no PR URL provided)';

  const itemRows = data.items.map(item =>
    `<tr>
      <td style="padding: 8px; border: 1px solid #e2e8f0;">${item.title}</td>
      <td style="padding: 8px; border: 1px solid #e2e8f0;">${item.source}</td>
      <td style="padding: 8px; border: 1px solid #e2e8f0;">${item.daemonScore || '?'}/10</td>
      <td style="padding: 8px; border: 1px solid #e2e8f0;">${item.reason}</td>
    </tr>`
  ).join('\n');

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 700px;">
      <h2 style="color: #1e293b;">Auto-Triage Escalations — Week of ${data.weekOf}</h2>
      <p>${data.items.length} item(s) need your review.</p>

      <table style="border-collapse: collapse; width: 100%; margin: 16px 0;">
        <thead>
          <tr style="background: #f1f5f9;">
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Title</th>
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Source</th>
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Score</th>
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Reason</th>
          </tr>
        </thead>
        <tbody>
          ${itemRows}
        </tbody>
      </table>

      <p><a href="${prUrl}" style="color: #2563eb;">View PR</a></p>
      <p style="color: #64748b; font-size: 12px;">Generated by auto-triage workflow</p>
    </div>
  `;

  const resend = new Resend(apiKey);
  const result = await resend.emails.send({
    from: FROM_EMAIL,
    to: TO_EMAIL,
    subject: `[OpenOnco] ${data.items.length} triage escalation(s) — week of ${data.weekOf}`,
    html,
  });

  console.log('Escalation email sent:', result);
}

main().catch(err => {
  console.error('Failed to send escalation email:', err);
  // Don't fail the workflow over email
  process.exit(0);
});
